// Package dataplane provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package dataplane

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ScopedServerURLBaseUrlVariable is the `baseUrl` variable for ScopedServerURL
type ScopedServerURLBaseUrlVariable string

// ScopedServerURLBaseUrlVariableDefault is the default value for the `baseUrl` variable for ScopedServerURL
const ScopedServerURLBaseUrlVariableDefault = "http://localhost:8093/automation"

// ScopedServerURLEnvIdVariable is the `envId` variable for ScopedServerURL
type ScopedServerURLEnvIdVariable string

// ScopedServerURLEnvIdVariableDefault is the default value for the `envId` variable for ScopedServerURL
const ScopedServerURLEnvIdVariableDefault = "DEFAULT"

// ScopedServerURLOrgIdVariable is the `orgId` variable for ScopedServerURL
type ScopedServerURLOrgIdVariable string

// ScopedServerURLOrgIdVariableDefault is the default value for the `orgId` variable for ScopedServerURL
const ScopedServerURLOrgIdVariableDefault = "DEFAULT"

// NewScopedServerURL constructs the Server URL for Organization and environment scoped Automation API, with the provided variables.
func NewScopedServerURL(baseUrl ScopedServerURLBaseUrlVariable, envId ScopedServerURLEnvIdVariable, orgId ScopedServerURLOrgIdVariable) (string, error) {

	u := "{baseUrl}/organizations/{orgId}/environments/{envId}"

	u = strings.ReplaceAll(u, "{baseUrl}", string(baseUrl))
	u = strings.ReplaceAll(u, "{envId}", string(envId))
	u = strings.ReplaceAll(u, "{orgId}", string(orgId))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// AutomationDataPlane A data plane managed by the Automation API. Data planes store the runtime data of the domains bound to them. The id field is the stable, immutable identity used for idempotent create-or-update.
type AutomationDataPlane = DataPlane

// DataPlane A data plane managed by the Automation API. Data planes store the runtime data of the domains bound to them. The id field is the stable, immutable identity used for idempotent create-or-update.
type DataPlane struct {
	// Configuration Connection settings. Write-only: it can hold credentials.
	//
	// Example: {"mongodb":{"dbname":"gravitee-am-acme","host":"mongo","port":27017}}
	Configuration *map[string]interface{} `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// Database Name of the database the configuration points at. Read-only.
	//
	// Example: gravitee-am-acme
	Database *string `json:"database,omitempty"`

	// EnvironmentId Identifier of the environment the data plane belongs to. Read-only.
	//
	// Example: DEFAULT
	EnvironmentId *string `json:"environmentId,omitempty"`

	// GatewayUrl Base URL of the gateway serving the domains bound to this data plane.
	//
	// Example: https://gateway-eu.example.com
	GatewayUrl *string `json:"gatewayUrl,omitempty"`

	// Hosts Hosts the configuration points at, as host:port. Read-only.
	//
	// Example: ["mongo:27017"]
	Hosts *[]string `json:"hosts,omitempty"`

	// Id Stable, immutable identifier for the data plane within its environment. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. This is the value a domain's dataPlaneId refers to.
	//
	// Example: acme-eu
	Id string `json:"id"`

	// Name Human-readable name of the data plane.
	//
	// Example: ACME EU data plane
	Name *string `json:"name,omitempty"`

	// OrganizationId Identifier of the organization the data plane belongs to. Read-only.
	//
	// Example: DEFAULT
	OrganizationId *string `json:"organizationId,omitempty"`

	// Type Data plane plugin type identifier, matching the dataplane-am-<type> plugin. Immutable after creation.
	//
	// Example: mongodb
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// UpsertDataPlaneJSONRequestBody defines body for UpsertDataPlane for application/json ContentType.
type UpsertDataPlaneJSONRequestBody = AutomationDataPlane

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListDataPlanes List an environment's data planes
	//
	// Returns all data planes managed by the Automation API in the environment. Data planes provisioned outside the Automation API are not returned.
	//
	// Corresponds with GET /dataplanes (the `ListDataPlanes` operationId).
	ListDataPlanes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertDataPlaneWithBody Create or update a data plane
	//
	// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
	UpsertDataPlaneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertDataPlane Create or update a data plane
	//
	// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
	UpsertDataPlane(ctx context.Context, body UpsertDataPlaneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDataPlane Delete a data plane
	//
	// Deletes an Automation-managed data plane by its id. Deleting a data plane that does not exist also returns 204.
	//
	// Corresponds with DELETE /dataplanes/{dataPlaneId} (the `DeleteDataPlane` operationId).
	DeleteDataPlane(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDataPlane Get a data plane
	//
	// Retrieves a single Automation-managed data plane by its id.
	//
	// Corresponds with GET /dataplanes/{dataPlaneId} (the `GetDataPlane` operationId).
	GetDataPlane(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListDataPlanes List an environment's data planes
//
// Returns all data planes managed by the Automation API in the environment. Data planes provisioned outside the Automation API are not returned.
//
// Corresponds with GET /dataplanes (the `ListDataPlanes` operationId).
func (c *Client) ListDataPlanes(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDataPlanesRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertDataPlaneWithBody Create or update a data plane
//
// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
func (c *Client) UpsertDataPlaneWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertDataPlaneRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertDataPlane Create or update a data plane
//
// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
func (c *Client) UpsertDataPlane(ctx context.Context, body UpsertDataPlaneJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertDataPlaneRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteDataPlane Delete a data plane
//
// Deletes an Automation-managed data plane by its id. Deleting a data plane that does not exist also returns 204.
//
// Corresponds with DELETE /dataplanes/{dataPlaneId} (the `DeleteDataPlane` operationId).
func (c *Client) DeleteDataPlane(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDataPlaneRequest(c.Server, dataPlaneId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDataPlane Get a data plane
//
// Retrieves a single Automation-managed data plane by its id.
//
// Corresponds with GET /dataplanes/{dataPlaneId} (the `GetDataPlane` operationId).
func (c *Client) GetDataPlane(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDataPlaneRequest(c.Server, dataPlaneId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDataPlanesRequest constructs an http.Request for the ListDataPlanes method
func NewListDataPlanesRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dataplanes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertDataPlaneRequest calls the generic UpsertDataPlane builder with application/json body
func NewUpsertDataPlaneRequest(server string, body UpsertDataPlaneJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertDataPlaneRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertDataPlaneRequestWithBody constructs an http.Request for the UpsertDataPlane method, with any body, and a specified content type
func NewUpsertDataPlaneRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dataplanes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDataPlaneRequest constructs an http.Request for the DeleteDataPlane method
func NewDeleteDataPlaneRequest(server string, dataPlaneId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dataPlaneId", dataPlaneId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dataplanes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDataPlaneRequest constructs an http.Request for the GetDataPlane method
func NewGetDataPlaneRequest(server string, dataPlaneId string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "dataPlaneId", dataPlaneId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/dataplanes/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListDataPlanesWithResponse List an environment's data planes
	//
	// Returns all data planes managed by the Automation API in the environment. Data planes provisioned outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /dataplanes (the `ListDataPlanes` operationId).
	ListDataPlanesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDataPlanesResponse, error)

	// UpsertDataPlaneWithBodyWithResponse Create or update a data plane
	//
	// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
	UpsertDataPlaneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertDataPlaneResponse, error)

	// UpsertDataPlaneWithResponse Create or update a data plane
	//
	// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
	UpsertDataPlaneWithResponse(ctx context.Context, body UpsertDataPlaneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertDataPlaneResponse, error)

	// DeleteDataPlaneWithResponse Delete a data plane
	//
	// Deletes an Automation-managed data plane by its id. Deleting a data plane that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /dataplanes/{dataPlaneId} (the `DeleteDataPlane` operationId).
	DeleteDataPlaneWithResponse(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*DeleteDataPlaneResponse, error)

	// GetDataPlaneWithResponse Get a data plane
	//
	// Retrieves a single Automation-managed data plane by its id.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /dataplanes/{dataPlaneId} (the `GetDataPlane` operationId).
	GetDataPlaneWithResponse(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*GetDataPlaneResponse, error)
}

type ListDataPlanesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationDataPlane
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDataPlanesResponse) GetJSON200() *[]AutomationDataPlane {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListDataPlanesResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListDataPlanesResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListDataPlanesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDataPlanesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDataPlanesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDataPlanesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpsertDataPlaneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationDataPlane
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertDataPlaneResponse) GetJSON200() *AutomationDataPlane {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpsertDataPlaneResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpsertDataPlaneResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpsertDataPlaneResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r UpsertDataPlaneResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r UpsertDataPlaneResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertDataPlaneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertDataPlaneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertDataPlaneResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDataPlaneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON409 the response for an HTTP 409 `application/json` response
	JSON409 *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteDataPlaneResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON409 returns the response for an HTTP 409 `application/json` response
func (r DeleteDataPlaneResponse) GetJSON409() *Error {
	return r.JSON409
}

// GetBody returns the raw response body bytes
func (r DeleteDataPlaneResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteDataPlaneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDataPlaneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDataPlaneResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDataPlaneResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationDataPlane
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDataPlaneResponse) GetJSON200() *AutomationDataPlane {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetDataPlaneResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDataPlaneResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetDataPlaneResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDataPlaneResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDataPlaneResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDataPlaneResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDataPlanesWithResponse List an environment's data planes
//
// Returns all data planes managed by the Automation API in the environment. Data planes provisioned outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /dataplanes (the `ListDataPlanes` operationId).
func (c *ClientWithResponses) ListDataPlanesWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDataPlanesResponse, error) {
	rsp, err := c.ListDataPlanes(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDataPlanesResponse(rsp)
}

// UpsertDataPlaneWithBodyWithResponse Create or update a data plane
//
// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
func (c *ClientWithResponses) UpsertDataPlaneWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertDataPlaneResponse, error) {
	rsp, err := c.UpsertDataPlaneWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertDataPlaneResponse(rsp)
}

// UpsertDataPlaneWithResponse Create or update a data plane
//
// Idempotent create-or-update. Uses the id field in the body to identify the data plane within the environment. The type is immutable, and the organization and environment come from the path. An id: reference updates a data plane the Automation API does not manage, and cannot create one.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /dataplanes (the `UpsertDataPlane` operationId).
func (c *ClientWithResponses) UpsertDataPlaneWithResponse(ctx context.Context, body UpsertDataPlaneJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertDataPlaneResponse, error) {
	rsp, err := c.UpsertDataPlane(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertDataPlaneResponse(rsp)
}

// DeleteDataPlaneWithResponse Delete a data plane
//
// Deletes an Automation-managed data plane by its id. Deleting a data plane that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /dataplanes/{dataPlaneId} (the `DeleteDataPlane` operationId).
func (c *ClientWithResponses) DeleteDataPlaneWithResponse(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*DeleteDataPlaneResponse, error) {
	rsp, err := c.DeleteDataPlane(ctx, dataPlaneId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDataPlaneResponse(rsp)
}

// GetDataPlaneWithResponse Get a data plane
//
// Retrieves a single Automation-managed data plane by its id.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /dataplanes/{dataPlaneId} (the `GetDataPlane` operationId).
func (c *ClientWithResponses) GetDataPlaneWithResponse(ctx context.Context, dataPlaneId string, reqEditors ...RequestEditorFn) (*GetDataPlaneResponse, error) {
	rsp, err := c.GetDataPlane(ctx, dataPlaneId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDataPlaneResponse(rsp)
}

// ParseListDataPlanesResponse parses an HTTP response from a ListDataPlanesWithResponse call
func ParseListDataPlanesResponse(rsp *http.Response) (*ListDataPlanesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDataPlanesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationDataPlane
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpsertDataPlaneResponse parses an HTTP response from a UpsertDataPlaneWithResponse call
func ParseUpsertDataPlaneResponse(rsp *http.Response) (*UpsertDataPlaneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertDataPlaneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationDataPlane
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseDeleteDataPlaneResponse parses an HTTP response from a DeleteDataPlaneWithResponse call
func ParseDeleteDataPlaneResponse(rsp *http.Response) (*DeleteDataPlaneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDataPlaneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetDataPlaneResponse parses an HTTP response from a GetDataPlaneWithResponse call
func ParseGetDataPlaneResponse(rsp *http.Response) (*GetDataPlaneResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDataPlaneResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationDataPlane
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
