// Package identityprovider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityprovider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ScopedServerURLBaseUrlVariable is the `baseUrl` variable for ScopedServerURL
type ScopedServerURLBaseUrlVariable string

// ScopedServerURLBaseUrlVariableDefault is the default value for the `baseUrl` variable for ScopedServerURL
const ScopedServerURLBaseUrlVariableDefault = "http://localhost:8093/automation"

// ScopedServerURLEnvIdVariable is the `envId` variable for ScopedServerURL
type ScopedServerURLEnvIdVariable string

// ScopedServerURLEnvIdVariableDefault is the default value for the `envId` variable for ScopedServerURL
const ScopedServerURLEnvIdVariableDefault = "DEFAULT"

// ScopedServerURLOrgIdVariable is the `orgId` variable for ScopedServerURL
type ScopedServerURLOrgIdVariable string

// ScopedServerURLOrgIdVariableDefault is the default value for the `orgId` variable for ScopedServerURL
const ScopedServerURLOrgIdVariableDefault = "DEFAULT"

// NewScopedServerURL constructs the Server URL for Organization and environment scoped Automation API, with the provided variables.
func NewScopedServerURL(baseUrl ScopedServerURLBaseUrlVariable, envId ScopedServerURLEnvIdVariable, orgId ScopedServerURLOrgIdVariable) (string, error) {

	u := "{baseUrl}/organizations/{orgId}/environments/{envId}"

	u = strings.ReplaceAll(u, "{baseUrl}", string(baseUrl))
	u = strings.ReplaceAll(u, "{envId}", string(envId))
	u = strings.ReplaceAll(u, "{orgId}", string(orgId))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// AutomationIdentityProvider An identity provider managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationIdentityProvider = IdentityProvider

// IdentityProvider An identity provider managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type IdentityProvider struct {
	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected identity provider type.
	//
	// Example: {"users":[{"username":"admin","password":"..."}]}
	Configuration *string `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DomainWhitelist Email domains allowed to authenticate through this identity provider. When set, users whose email domain is not listed are rejected.
	//
	// Example: ["example.com"]
	DomainWhitelist *[]string `json:"domainWhitelist,omitempty"`

	// GroupMapper Group mapper: assigns AM groups based on provider attribute values. Each entry maps a group to the user attribute expressions that grant it.
	GroupMapper *map[string][]string `json:"groupMapper,omitempty"`

	// Key Stable, immutable identifier for the identity provider within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the identity provider on create-or-update.
	//
	// Example: corporate-ldap
	Key string `json:"key"`

	// Mappers Attribute mappers: maps provider claims to AM user profile attributes.
	//
	// Example: {"email":"email","sub":"username"}
	Mappers *map[string]string `json:"mappers,omitempty"`

	// Name Human-readable name of the identity provider.
	//
	// Example: Corporate LDAP
	Name *string `json:"name,omitempty"`

	// RoleMapper Role mapper: assigns AM roles based on provider attribute values. Each entry maps a role to the user attribute expressions that grant it.
	RoleMapper *map[string][]string `json:"roleMapper,omitempty"`

	// System Whether this is the domain's system identity provider. Immutable after creation. When true, only key is required; the identity provider is built from the domains.identities.default.* system settings and the name, type, and configuration fields are ignored.
	System *bool `json:"system,omitempty"`

	// Type Identity provider plugin type identifier. Immutable after creation.
	//
	// Example: inline-am-idp
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// UpsertIdentityProviderJSONRequestBody defines body for UpsertIdentityProvider for application/json ContentType.
type UpsertIdentityProviderJSONRequestBody = AutomationIdentityProvider

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListIdentityProviders List a domain's identity providers
	//
	// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
	//
	// Corresponds with GET /domains/{domainKey}/identities (the `ListIdentityProviders` operationId).
	ListIdentityProviders(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertIdentityProviderWithBody Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
	UpsertIdentityProviderWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertIdentityProvider Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
	UpsertIdentityProvider(ctx context.Context, domainKey string, body UpsertIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteIdentityProvider Delete an identity provider
	//
	// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
	//
	// Corresponds with DELETE /domains/{domainKey}/identities/{identityKey} (the `DeleteIdentityProvider` operationId).
	DeleteIdentityProvider(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIdentityProvider Get an identity provider
	//
	// Retrieves a single Automation-managed identity provider by its key.
	//
	// Corresponds with GET /domains/{domainKey}/identities/{identityKey} (the `GetIdentityProvider` operationId).
	GetIdentityProvider(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListIdentityProviders List a domain's identity providers
//
// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
//
// Corresponds with GET /domains/{domainKey}/identities (the `ListIdentityProviders` operationId).
func (c *Client) ListIdentityProviders(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListIdentityProvidersRequest(c.Server, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertIdentityProviderWithBody Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
func (c *Client) UpsertIdentityProviderWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertIdentityProviderRequestWithBody(c.Server, domainKey, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertIdentityProvider Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
func (c *Client) UpsertIdentityProvider(ctx context.Context, domainKey string, body UpsertIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertIdentityProviderRequest(c.Server, domainKey, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteIdentityProvider Delete an identity provider
//
// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
//
// Corresponds with DELETE /domains/{domainKey}/identities/{identityKey} (the `DeleteIdentityProvider` operationId).
func (c *Client) DeleteIdentityProvider(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteIdentityProviderRequest(c.Server, domainKey, identityKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetIdentityProvider Get an identity provider
//
// Retrieves a single Automation-managed identity provider by its key.
//
// Corresponds with GET /domains/{domainKey}/identities/{identityKey} (the `GetIdentityProvider` operationId).
func (c *Client) GetIdentityProvider(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIdentityProviderRequest(c.Server, domainKey, identityKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListIdentityProvidersRequest constructs an http.Request for the ListIdentityProviders method
func NewListIdentityProvidersRequest(server string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/identities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertIdentityProviderRequest calls the generic UpsertIdentityProvider builder with application/json body
func NewUpsertIdentityProviderRequest(server string, domainKey string, body UpsertIdentityProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertIdentityProviderRequestWithBody(server, domainKey, "application/json", bodyReader)
}

// NewUpsertIdentityProviderRequestWithBody constructs an http.Request for the UpsertIdentityProvider method, with any body, and a specified content type
func NewUpsertIdentityProviderRequestWithBody(server string, domainKey string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/identities", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteIdentityProviderRequest constructs an http.Request for the DeleteIdentityProvider method
func NewDeleteIdentityProviderRequest(server string, domainKey string, identityKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "identityKey", identityKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/identities/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetIdentityProviderRequest constructs an http.Request for the GetIdentityProvider method
func NewGetIdentityProviderRequest(server string, domainKey string, identityKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "identityKey", identityKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/identities/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListIdentityProvidersWithResponse List a domain's identity providers
	//
	// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/identities (the `ListIdentityProviders` operationId).
	ListIdentityProvidersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*ListIdentityProvidersResponse, error)

	// UpsertIdentityProviderWithBodyWithResponse Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
	UpsertIdentityProviderWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertIdentityProviderResponse, error)

	// UpsertIdentityProviderWithResponse Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
	UpsertIdentityProviderWithResponse(ctx context.Context, domainKey string, body UpsertIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertIdentityProviderResponse, error)

	// DeleteIdentityProviderWithResponse Delete an identity provider
	//
	// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /domains/{domainKey}/identities/{identityKey} (the `DeleteIdentityProvider` operationId).
	DeleteIdentityProviderWithResponse(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*DeleteIdentityProviderResponse, error)

	// GetIdentityProviderWithResponse Get an identity provider
	//
	// Retrieves a single Automation-managed identity provider by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/identities/{identityKey} (the `GetIdentityProvider` operationId).
	GetIdentityProviderWithResponse(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*GetIdentityProviderResponse, error)
}

type ListIdentityProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationIdentityProvider
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListIdentityProvidersResponse) GetJSON200() *[]AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListIdentityProvidersResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListIdentityProvidersResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r ListIdentityProvidersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListIdentityProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListIdentityProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListIdentityProvidersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpsertIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationIdentityProvider
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertIdentityProviderResponse) GetJSON200() *AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpsertIdentityProviderResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpsertIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpsertIdentityProviderResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r UpsertIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteIdentityProviderResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationIdentityProvider
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetIdentityProviderResponse) GetJSON200() *AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetIdentityProviderResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListIdentityProvidersWithResponse List a domain's identity providers
//
// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/identities (the `ListIdentityProviders` operationId).
func (c *ClientWithResponses) ListIdentityProvidersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*ListIdentityProvidersResponse, error) {
	rsp, err := c.ListIdentityProviders(ctx, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListIdentityProvidersResponse(rsp)
}

// UpsertIdentityProviderWithBodyWithResponse Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
func (c *ClientWithResponses) UpsertIdentityProviderWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertIdentityProviderResponse, error) {
	rsp, err := c.UpsertIdentityProviderWithBody(ctx, domainKey, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertIdentityProviderResponse(rsp)
}

// UpsertIdentityProviderWithResponse Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/identities (the `UpsertIdentityProvider` operationId).
func (c *ClientWithResponses) UpsertIdentityProviderWithResponse(ctx context.Context, domainKey string, body UpsertIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertIdentityProviderResponse, error) {
	rsp, err := c.UpsertIdentityProvider(ctx, domainKey, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertIdentityProviderResponse(rsp)
}

// DeleteIdentityProviderWithResponse Delete an identity provider
//
// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /domains/{domainKey}/identities/{identityKey} (the `DeleteIdentityProvider` operationId).
func (c *ClientWithResponses) DeleteIdentityProviderWithResponse(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*DeleteIdentityProviderResponse, error) {
	rsp, err := c.DeleteIdentityProvider(ctx, domainKey, identityKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteIdentityProviderResponse(rsp)
}

// GetIdentityProviderWithResponse Get an identity provider
//
// Retrieves a single Automation-managed identity provider by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/identities/{identityKey} (the `GetIdentityProvider` operationId).
func (c *ClientWithResponses) GetIdentityProviderWithResponse(ctx context.Context, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*GetIdentityProviderResponse, error) {
	rsp, err := c.GetIdentityProvider(ctx, domainKey, identityKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIdentityProviderResponse(rsp)
}

// ParseListIdentityProvidersResponse parses an HTTP response from a ListIdentityProvidersWithResponse call
func ParseListIdentityProvidersResponse(rsp *http.Response) (*ListIdentityProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListIdentityProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpsertIdentityProviderResponse parses an HTTP response from a UpsertIdentityProviderWithResponse call
func ParseUpsertIdentityProviderResponse(rsp *http.Response) (*UpsertIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteIdentityProviderResponse parses an HTTP response from a DeleteIdentityProviderWithResponse call
func ParseDeleteIdentityProviderResponse(rsp *http.Response) (*DeleteIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetIdentityProviderResponse parses an HTTP response from a GetIdentityProviderWithResponse call
func ParseGetIdentityProviderResponse(rsp *http.Response) (*GetIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
