// Package certificate provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package certificate

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AutomationCertificate A certificate managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationCertificate struct {
	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected certificate type.
	//
	// Example: {"jks":{"content":"...","name":"keystore.jks"},"storepass":"secret","alias":"mykey","keypass":"secret"}
	Configuration *string `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// ExpiresAt Expiry timestamp (ISO-8601 / RFC 3339, UTC), when known for the certificate type. Read-only.
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`

	// Key Stable, immutable identifier for the certificate within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the certificate on create-or-update.
	//
	// Example: signing-cert
	Key string `json:"key"`

	// Name Human-readable name of the certificate.
	//
	// Example: Signing certificate
	Name *string `json:"name,omitempty"`

	// System Whether this is the domain's system certificate. Immutable after creation. When true, only key is required; the certificate is built from the domains.certificates.default.* system settings and the name, type, and configuration fields are ignored.
	System *bool `json:"system,omitempty"`

	// Type Certificate plugin type identifier. Immutable after creation.
	//
	// Example: javakeystore-am-certificate
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// AutomationCreateOrUpdateCertificateJSONRequestBody defines body for AutomationCreateOrUpdateCertificate for application/json ContentType.
type AutomationCreateOrUpdateCertificateJSONRequestBody = AutomationCertificate

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// AutomationListCertificates List a domain's certificates
	//
	// Returns all certificates managed by the Automation API under the domain. Certificates created outside the Automation API are not returned.
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationListCertificates` operationId).
	AutomationListCertificates(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateCertificateWithBody Create or update a certificate
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
	AutomationCreateOrUpdateCertificateWithBody(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateCertificate Create or update a certificate
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
	AutomationCreateOrUpdateCertificate(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationDeleteCertificate Delete a certificate
	//
	// Deletes an Automation-managed certificate by its key. Deleting a certificate that does not exist also returns 204.
	//
	// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationDeleteCertificate` operationId).
	AutomationDeleteCertificate(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationGetCertificate Get a certificate
	//
	// Retrieves a single Automation-managed certificate by its key.
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationGetCertificate` operationId).
	AutomationGetCertificate(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// AutomationListCertificates List a domain's certificates
//
// Returns all certificates managed by the Automation API under the domain. Certificates created outside the Automation API are not returned.
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationListCertificates` operationId).
func (c *Client) AutomationListCertificates(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationListCertificatesRequest(c.Server, orgId, envId, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateCertificateWithBody Create or update a certificate
//
// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
func (c *Client) AutomationCreateOrUpdateCertificateWithBody(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateCertificateRequestWithBody(c.Server, orgId, envId, domainKey, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateCertificate Create or update a certificate
//
// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
func (c *Client) AutomationCreateOrUpdateCertificate(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateCertificateRequest(c.Server, orgId, envId, domainKey, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationDeleteCertificate Delete a certificate
//
// Deletes an Automation-managed certificate by its key. Deleting a certificate that does not exist also returns 204.
//
// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationDeleteCertificate` operationId).
func (c *Client) AutomationDeleteCertificate(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationDeleteCertificateRequest(c.Server, orgId, envId, domainKey, certKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationGetCertificate Get a certificate
//
// Retrieves a single Automation-managed certificate by its key.
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationGetCertificate` operationId).
func (c *Client) AutomationGetCertificate(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationGetCertificateRequest(c.Server, orgId, envId, domainKey, certKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAutomationListCertificatesRequest constructs an http.Request for the AutomationListCertificates method
func NewAutomationListCertificatesRequest(server string, orgId string, envId string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/certificates", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationCreateOrUpdateCertificateRequest calls the generic AutomationCreateOrUpdateCertificate builder with application/json body
func NewAutomationCreateOrUpdateCertificateRequest(server string, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateCertificateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAutomationCreateOrUpdateCertificateRequestWithBody(server, orgId, envId, domainKey, "application/json", bodyReader)
}

// NewAutomationCreateOrUpdateCertificateRequestWithBody constructs an http.Request for the AutomationCreateOrUpdateCertificate method, with any body, and a specified content type
func NewAutomationCreateOrUpdateCertificateRequestWithBody(server string, orgId string, envId string, domainKey string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/certificates", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAutomationDeleteCertificateRequest constructs an http.Request for the AutomationDeleteCertificate method
func NewAutomationDeleteCertificateRequest(server string, orgId string, envId string, domainKey string, certKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithOptions("simple", false, "certKey", certKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/certificates/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationGetCertificateRequest constructs an http.Request for the AutomationGetCertificate method
func NewAutomationGetCertificateRequest(server string, orgId string, envId string, domainKey string, certKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithOptions("simple", false, "certKey", certKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/certificates/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// AutomationListCertificatesWithResponse List a domain's certificates
	//
	// Returns all certificates managed by the Automation API under the domain. Certificates created outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationListCertificates` operationId).
	AutomationListCertificatesWithResponse(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListCertificatesResponse, error)

	// AutomationCreateOrUpdateCertificateWithBodyWithResponse Create or update a certificate
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
	AutomationCreateOrUpdateCertificateWithBodyWithResponse(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateCertificateResponse, error)

	// AutomationCreateOrUpdateCertificateWithResponse Create or update a certificate
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
	AutomationCreateOrUpdateCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateCertificateResponse, error)

	// AutomationDeleteCertificateWithResponse Delete a certificate
	//
	// Deletes an Automation-managed certificate by its key. Deleting a certificate that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationDeleteCertificate` operationId).
	AutomationDeleteCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteCertificateResponse, error)

	// AutomationGetCertificateWithResponse Get a certificate
	//
	// Retrieves a single Automation-managed certificate by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationGetCertificate` operationId).
	AutomationGetCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*AutomationGetCertificateResponse, error)
}

type AutomationListCertificatesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationCertificate
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationListCertificatesResponse) GetJSON200() *[]AutomationCertificate {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationListCertificatesResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationListCertificatesResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationListCertificatesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationListCertificatesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationListCertificatesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationListCertificatesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationCreateOrUpdateCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationCertificate
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationCreateOrUpdateCertificateResponse) GetJSON200() *AutomationCertificate {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r AutomationCreateOrUpdateCertificateResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationCreateOrUpdateCertificateResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationCreateOrUpdateCertificateResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationCreateOrUpdateCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationCreateOrUpdateCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationCreateOrUpdateCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationCreateOrUpdateCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationDeleteCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationDeleteCertificateResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r AutomationDeleteCertificateResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r AutomationDeleteCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationDeleteCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationDeleteCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationDeleteCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationGetCertificateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationCertificate
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationGetCertificateResponse) GetJSON200() *AutomationCertificate {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationGetCertificateResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationGetCertificateResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationGetCertificateResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationGetCertificateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationGetCertificateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationGetCertificateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AutomationListCertificatesWithResponse List a domain's certificates
//
// Returns all certificates managed by the Automation API under the domain. Certificates created outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationListCertificates` operationId).
func (c *ClientWithResponses) AutomationListCertificatesWithResponse(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListCertificatesResponse, error) {
	rsp, err := c.AutomationListCertificates(ctx, orgId, envId, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationListCertificatesResponse(rsp)
}

// AutomationCreateOrUpdateCertificateWithBodyWithResponse Create or update a certificate
//
// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateCertificateWithBodyWithResponse(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateCertificateResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateCertificateWithBody(ctx, orgId, envId, domainKey, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateCertificateResponse(rsp)
}

// AutomationCreateOrUpdateCertificateWithResponse Create or update a certificate
//
// Idempotent create-or-update. Uses the key field in the body to identify the certificate within the domain. Re-applying an unchanged definition is a no-op. The system flag is immutable; changing it requires deleting and recreating the certificate.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates (the `AutomationCreateOrUpdateCertificate` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateCertificateJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateCertificateResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateCertificate(ctx, orgId, envId, domainKey, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateCertificateResponse(rsp)
}

// AutomationDeleteCertificateWithResponse Delete a certificate
//
// Deletes an Automation-managed certificate by its key. Deleting a certificate that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationDeleteCertificate` operationId).
func (c *ClientWithResponses) AutomationDeleteCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteCertificateResponse, error) {
	rsp, err := c.AutomationDeleteCertificate(ctx, orgId, envId, domainKey, certKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationDeleteCertificateResponse(rsp)
}

// AutomationGetCertificateWithResponse Get a certificate
//
// Retrieves a single Automation-managed certificate by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/certificates/{certKey} (the `AutomationGetCertificate` operationId).
func (c *ClientWithResponses) AutomationGetCertificateWithResponse(ctx context.Context, orgId string, envId string, domainKey string, certKey string, reqEditors ...RequestEditorFn) (*AutomationGetCertificateResponse, error) {
	rsp, err := c.AutomationGetCertificate(ctx, orgId, envId, domainKey, certKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationGetCertificateResponse(rsp)
}

// ParseAutomationListCertificatesResponse parses an HTTP response from a AutomationListCertificatesWithResponse call
func ParseAutomationListCertificatesResponse(rsp *http.Response) (*AutomationListCertificatesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationListCertificatesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationCertificate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationCreateOrUpdateCertificateResponse parses an HTTP response from a AutomationCreateOrUpdateCertificateWithResponse call
func ParseAutomationCreateOrUpdateCertificateResponse(rsp *http.Response) (*AutomationCreateOrUpdateCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationCreateOrUpdateCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationCertificate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationDeleteCertificateResponse parses an HTTP response from a AutomationDeleteCertificateWithResponse call
func ParseAutomationDeleteCertificateResponse(rsp *http.Response) (*AutomationDeleteCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationDeleteCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAutomationGetCertificateResponse parses an HTTP response from a AutomationGetCertificateWithResponse call
func ParseAutomationGetCertificateResponse(rsp *http.Response) (*AutomationGetCertificateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationGetCertificateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationCertificate
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
