// Package reporter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package reporter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ScopedServerURLBaseUrlVariable is the `baseUrl` variable for ScopedServerURL
type ScopedServerURLBaseUrlVariable string

// ScopedServerURLBaseUrlVariableDefault is the default value for the `baseUrl` variable for ScopedServerURL
const ScopedServerURLBaseUrlVariableDefault = "http://localhost:8093/automation"

// ScopedServerURLEnvIdVariable is the `envId` variable for ScopedServerURL
type ScopedServerURLEnvIdVariable string

// ScopedServerURLEnvIdVariableDefault is the default value for the `envId` variable for ScopedServerURL
const ScopedServerURLEnvIdVariableDefault = "DEFAULT"

// ScopedServerURLOrgIdVariable is the `orgId` variable for ScopedServerURL
type ScopedServerURLOrgIdVariable string

// ScopedServerURLOrgIdVariableDefault is the default value for the `orgId` variable for ScopedServerURL
const ScopedServerURLOrgIdVariableDefault = "DEFAULT"

// NewScopedServerURL constructs the Server URL for Organization and environment scoped Automation API, with the provided variables.
func NewScopedServerURL(baseUrl ScopedServerURLBaseUrlVariable, envId ScopedServerURLEnvIdVariable, orgId ScopedServerURLOrgIdVariable) (string, error) {

	u := "{baseUrl}/organizations/{orgId}/environments/{envId}"

	u = strings.ReplaceAll(u, "{baseUrl}", string(baseUrl))
	u = strings.ReplaceAll(u, "{envId}", string(envId))
	u = strings.ReplaceAll(u, "{orgId}", string(orgId))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// AutomationReporter A reporter managed under a domain by the Automation API. Reporters persist audit events to a backend. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationReporter = Reporter

// Reporter A reporter managed under a domain by the Automation API. Reporters persist audit events to a backend. The key field is the stable, immutable identity used for idempotent create-or-update.
type Reporter struct {
	// AttributeMappings Additional attributes exported alongside the regular audit payload. Each entry pairs an expression read from the audit context with the field name its value is exported under. Ignored when system is true; a system reporter exports no additional attributes.
	AttributeMappings *[]ReporterAttributeMapping `json:"attributeMappings,omitempty"`

	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected reporter type.
	//
	// Example: {"bootstrapServers":"kafka:9092","topic":"audit"}
	Configuration *string `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DataType Category of data the reporter handles, derived from its type. Read-only.
	DataType *string `json:"dataType,omitempty"`

	// Enabled Whether the reporter is enabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Key Stable, immutable identifier for the reporter within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the reporter on create-or-update.
	//
	// Example: audit-kafka
	Key string `json:"key"`

	// Name Human-readable name of the reporter.
	//
	// Example: Audit events to Kafka
	Name *string `json:"name,omitempty"`

	// System Whether this is the domain's system reporter. Immutable after creation. When true, only key is required; the reporter is built from the domains.reporters.default.* and repository system settings and the name, type, configuration, and attributeMappings fields are ignored.
	System *bool `json:"system,omitempty"`

	// Type Reporter plugin type identifier. Immutable after creation.
	//
	// Example: reporter-am-kafka
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// ReporterAttributeMapping Exports one additional attribute, read from the audit context by expression, under a chosen field name.
type ReporterAttributeMapping struct {
	// ExportedName The name the evaluated value takes on the exported payload.
	//
	// Example: user_sub
	ExportedName *string `json:"exportedName,omitempty"`

	// Expression Expression evaluated against the audit context.
	//
	// Example: {#context.attributes['user'].additionalInformation['sub']}
	Expression *string `json:"expression,omitempty"`
}

// UpsertReporterJSONRequestBody defines body for UpsertReporter for application/json ContentType.
type UpsertReporterJSONRequestBody = AutomationReporter

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListReporters List a domain's reporters
	//
	// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
	//
	// Corresponds with GET /domains/{domainKey}/reporters (the `ListReporters` operationId).
	ListReporters(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertReporterWithBody Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
	UpsertReporterWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertReporter Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
	UpsertReporter(ctx context.Context, domainKey string, body UpsertReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteReporter Delete a reporter
	//
	// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
	//
	// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `DeleteReporter` operationId).
	DeleteReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetReporter Get a reporter
	//
	// Retrieves a single Automation-managed reporter by its key.
	//
	// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `GetReporter` operationId).
	GetReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListReporters List a domain's reporters
//
// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
//
// Corresponds with GET /domains/{domainKey}/reporters (the `ListReporters` operationId).
func (c *Client) ListReporters(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListReportersRequest(c.Server, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertReporterWithBody Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
func (c *Client) UpsertReporterWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertReporterRequestWithBody(c.Server, domainKey, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertReporter Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
func (c *Client) UpsertReporter(ctx context.Context, domainKey string, body UpsertReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertReporterRequest(c.Server, domainKey, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteReporter Delete a reporter
//
// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
//
// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `DeleteReporter` operationId).
func (c *Client) DeleteReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteReporterRequest(c.Server, domainKey, reporterKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetReporter Get a reporter
//
// Retrieves a single Automation-managed reporter by its key.
//
// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `GetReporter` operationId).
func (c *Client) GetReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetReporterRequest(c.Server, domainKey, reporterKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListReportersRequest constructs an http.Request for the ListReporters method
func NewListReportersRequest(server string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertReporterRequest calls the generic UpsertReporter builder with application/json body
func NewUpsertReporterRequest(server string, domainKey string, body UpsertReporterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertReporterRequestWithBody(server, domainKey, "application/json", bodyReader)
}

// NewUpsertReporterRequestWithBody constructs an http.Request for the UpsertReporter method, with any body, and a specified content type
func NewUpsertReporterRequestWithBody(server string, domainKey string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteReporterRequest constructs an http.Request for the DeleteReporter method
func NewDeleteReporterRequest(server string, domainKey string, reporterKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "reporterKey", reporterKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetReporterRequest constructs an http.Request for the GetReporter method
func NewGetReporterRequest(server string, domainKey string, reporterKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "reporterKey", reporterKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListReportersWithResponse List a domain's reporters
	//
	// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/reporters (the `ListReporters` operationId).
	ListReportersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*ListReportersResponse, error)

	// UpsertReporterWithBodyWithResponse Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
	UpsertReporterWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertReporterResponse, error)

	// UpsertReporterWithResponse Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
	UpsertReporterWithResponse(ctx context.Context, domainKey string, body UpsertReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertReporterResponse, error)

	// DeleteReporterWithResponse Delete a reporter
	//
	// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `DeleteReporter` operationId).
	DeleteReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*DeleteReporterResponse, error)

	// GetReporterWithResponse Get a reporter
	//
	// Retrieves a single Automation-managed reporter by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `GetReporter` operationId).
	GetReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*GetReporterResponse, error)
}

type ListReportersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationReporter
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListReportersResponse) GetJSON200() *[]AutomationReporter {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListReportersResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r ListReportersResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r ListReportersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListReportersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListReportersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListReportersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpsertReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationReporter
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertReporterResponse) GetJSON200() *AutomationReporter {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpsertReporterResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpsertReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r UpsertReporterResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r UpsertReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteReporterResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationReporter
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetReporterResponse) GetJSON200() *AutomationReporter {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetReporterResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListReportersWithResponse List a domain's reporters
//
// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/reporters (the `ListReporters` operationId).
func (c *ClientWithResponses) ListReportersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*ListReportersResponse, error) {
	rsp, err := c.ListReporters(ctx, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListReportersResponse(rsp)
}

// UpsertReporterWithBodyWithResponse Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
func (c *ClientWithResponses) UpsertReporterWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertReporterResponse, error) {
	rsp, err := c.UpsertReporterWithBody(ctx, domainKey, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertReporterResponse(rsp)
}

// UpsertReporterWithResponse Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `UpsertReporter` operationId).
func (c *ClientWithResponses) UpsertReporterWithResponse(ctx context.Context, domainKey string, body UpsertReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertReporterResponse, error) {
	rsp, err := c.UpsertReporter(ctx, domainKey, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertReporterResponse(rsp)
}

// DeleteReporterWithResponse Delete a reporter
//
// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `DeleteReporter` operationId).
func (c *ClientWithResponses) DeleteReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*DeleteReporterResponse, error) {
	rsp, err := c.DeleteReporter(ctx, domainKey, reporterKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteReporterResponse(rsp)
}

// GetReporterWithResponse Get a reporter
//
// Retrieves a single Automation-managed reporter by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `GetReporter` operationId).
func (c *ClientWithResponses) GetReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*GetReporterResponse, error) {
	rsp, err := c.GetReporter(ctx, domainKey, reporterKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetReporterResponse(rsp)
}

// ParseListReportersResponse parses an HTTP response from a ListReportersWithResponse call
func ParseListReportersResponse(rsp *http.Response) (*ListReportersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListReportersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpsertReporterResponse parses an HTTP response from a UpsertReporterWithResponse call
func ParseUpsertReporterResponse(rsp *http.Response) (*UpsertReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseDeleteReporterResponse parses an HTTP response from a DeleteReporterWithResponse call
func ParseDeleteReporterResponse(rsp *http.Response) (*DeleteReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetReporterResponse parses an HTTP response from a GetReporterWithResponse call
func ParseGetReporterResponse(rsp *http.Response) (*GetReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
