// Package identityprovider provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package identityprovider

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// AutomationIdentityProvider An identity provider managed under a domain by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationIdentityProvider struct {
	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected identity provider type.
	//
	// Example: {"users":[{"username":"admin","password":"..."}]}
	Configuration *string `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DomainWhitelist Email domains allowed to authenticate through this identity provider. When set, users whose email domain is not listed are rejected.
	//
	// Example: ["example.com"]
	DomainWhitelist *[]string `json:"domainWhitelist,omitempty"`

	// GroupMapper Group mapper: assigns AM groups based on provider attribute values. Each entry maps a group to the user attribute expressions that grant it.
	GroupMapper *map[string][]string `json:"groupMapper,omitempty"`

	// Key Stable, immutable identifier for the identity provider within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the identity provider on create-or-update.
	//
	// Example: corporate-ldap
	Key string `json:"key"`

	// Mappers Attribute mappers: maps provider claims to AM user profile attributes.
	//
	// Example: {"email":"email","sub":"username"}
	Mappers *map[string]string `json:"mappers,omitempty"`

	// Name Human-readable name of the identity provider.
	//
	// Example: Corporate LDAP
	Name *string `json:"name,omitempty"`

	// RoleMapper Role mapper: assigns AM roles based on provider attribute values. Each entry maps a role to the user attribute expressions that grant it.
	RoleMapper *map[string][]string `json:"roleMapper,omitempty"`

	// System Whether this is the domain's system identity provider. Immutable after creation. When true, only key is required; the identity provider is built from the domains.identities.default.* system settings and the name, type, and configuration fields are ignored.
	System *bool `json:"system,omitempty"`

	// Type Identity provider plugin type identifier. Immutable after creation.
	//
	// Example: inline-am-idp
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// AutomationCreateOrUpdateIdentityProviderJSONRequestBody defines body for AutomationCreateOrUpdateIdentityProvider for application/json ContentType.
type AutomationCreateOrUpdateIdentityProviderJSONRequestBody = AutomationIdentityProvider

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// AutomationListIdentityProviders List a domain's identity providers
	//
	// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationListIdentityProviders` operationId).
	AutomationListIdentityProviders(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateIdentityProviderWithBody Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
	AutomationCreateOrUpdateIdentityProviderWithBody(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateIdentityProvider Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
	AutomationCreateOrUpdateIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationDeleteIdentityProvider Delete an identity provider
	//
	// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
	//
	// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationDeleteIdentityProvider` operationId).
	AutomationDeleteIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationGetIdentityProvider Get an identity provider
	//
	// Retrieves a single Automation-managed identity provider by its key.
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationGetIdentityProvider` operationId).
	AutomationGetIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// AutomationListIdentityProviders List a domain's identity providers
//
// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationListIdentityProviders` operationId).
func (c *Client) AutomationListIdentityProviders(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationListIdentityProvidersRequest(c.Server, orgId, envId, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateIdentityProviderWithBody Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
func (c *Client) AutomationCreateOrUpdateIdentityProviderWithBody(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateIdentityProviderRequestWithBody(c.Server, orgId, envId, domainKey, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateIdentityProvider Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
func (c *Client) AutomationCreateOrUpdateIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateIdentityProviderRequest(c.Server, orgId, envId, domainKey, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationDeleteIdentityProvider Delete an identity provider
//
// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
//
// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationDeleteIdentityProvider` operationId).
func (c *Client) AutomationDeleteIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationDeleteIdentityProviderRequest(c.Server, orgId, envId, domainKey, identityKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationGetIdentityProvider Get an identity provider
//
// Retrieves a single Automation-managed identity provider by its key.
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationGetIdentityProvider` operationId).
func (c *Client) AutomationGetIdentityProvider(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationGetIdentityProviderRequest(c.Server, orgId, envId, domainKey, identityKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAutomationListIdentityProvidersRequest constructs an http.Request for the AutomationListIdentityProviders method
func NewAutomationListIdentityProvidersRequest(server string, orgId string, envId string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/identities", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationCreateOrUpdateIdentityProviderRequest calls the generic AutomationCreateOrUpdateIdentityProvider builder with application/json body
func NewAutomationCreateOrUpdateIdentityProviderRequest(server string, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateIdentityProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAutomationCreateOrUpdateIdentityProviderRequestWithBody(server, orgId, envId, domainKey, "application/json", bodyReader)
}

// NewAutomationCreateOrUpdateIdentityProviderRequestWithBody constructs an http.Request for the AutomationCreateOrUpdateIdentityProvider method, with any body, and a specified content type
func NewAutomationCreateOrUpdateIdentityProviderRequestWithBody(server string, orgId string, envId string, domainKey string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/identities", pathParam0, pathParam1, pathParam2)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAutomationDeleteIdentityProviderRequest constructs an http.Request for the AutomationDeleteIdentityProvider method
func NewAutomationDeleteIdentityProviderRequest(server string, orgId string, envId string, domainKey string, identityKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithOptions("simple", false, "identityKey", identityKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/identities/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationGetIdentityProviderRequest constructs an http.Request for the AutomationGetIdentityProvider method
func NewAutomationGetIdentityProviderRequest(server string, orgId string, envId string, domainKey string, identityKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "envId", envId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam2 string

	pathParam2, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam3 string

	pathParam3, err = runtime.StyleParamWithOptions("simple", false, "identityKey", identityKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/organizations/%s/environments/%s/domains/%s/identities/%s", pathParam0, pathParam1, pathParam2, pathParam3)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// AutomationListIdentityProvidersWithResponse List a domain's identity providers
	//
	// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationListIdentityProviders` operationId).
	AutomationListIdentityProvidersWithResponse(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListIdentityProvidersResponse, error)

	// AutomationCreateOrUpdateIdentityProviderWithBodyWithResponse Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
	AutomationCreateOrUpdateIdentityProviderWithBodyWithResponse(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateIdentityProviderResponse, error)

	// AutomationCreateOrUpdateIdentityProviderWithResponse Create or update an identity provider
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
	AutomationCreateOrUpdateIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateIdentityProviderResponse, error)

	// AutomationDeleteIdentityProviderWithResponse Delete an identity provider
	//
	// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationDeleteIdentityProvider` operationId).
	AutomationDeleteIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteIdentityProviderResponse, error)

	// AutomationGetIdentityProviderWithResponse Get an identity provider
	//
	// Retrieves a single Automation-managed identity provider by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationGetIdentityProvider` operationId).
	AutomationGetIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*AutomationGetIdentityProviderResponse, error)
}

type AutomationListIdentityProvidersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationIdentityProvider
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationListIdentityProvidersResponse) GetJSON200() *[]AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationListIdentityProvidersResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationListIdentityProvidersResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationListIdentityProvidersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationListIdentityProvidersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationListIdentityProvidersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationListIdentityProvidersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationCreateOrUpdateIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationIdentityProvider
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationCreateOrUpdateIdentityProviderResponse) GetJSON200() *AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r AutomationCreateOrUpdateIdentityProviderResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationCreateOrUpdateIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationCreateOrUpdateIdentityProviderResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationCreateOrUpdateIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationCreateOrUpdateIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationCreateOrUpdateIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationCreateOrUpdateIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationDeleteIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationDeleteIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r AutomationDeleteIdentityProviderResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r AutomationDeleteIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationDeleteIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationDeleteIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationDeleteIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationGetIdentityProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationIdentityProvider
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationGetIdentityProviderResponse) GetJSON200() *AutomationIdentityProvider {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationGetIdentityProviderResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationGetIdentityProviderResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationGetIdentityProviderResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationGetIdentityProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationGetIdentityProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationGetIdentityProviderResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AutomationListIdentityProvidersWithResponse List a domain's identity providers
//
// Returns all identity providers managed by the Automation API under the domain. Identity providers created outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationListIdentityProviders` operationId).
func (c *ClientWithResponses) AutomationListIdentityProvidersWithResponse(ctx context.Context, orgId string, envId string, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListIdentityProvidersResponse, error) {
	rsp, err := c.AutomationListIdentityProviders(ctx, orgId, envId, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationListIdentityProvidersResponse(rsp)
}

// AutomationCreateOrUpdateIdentityProviderWithBodyWithResponse Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateIdentityProviderWithBodyWithResponse(ctx context.Context, orgId string, envId string, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateIdentityProviderResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateIdentityProviderWithBody(ctx, orgId, envId, domainKey, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateIdentityProviderResponse(rsp)
}

// AutomationCreateOrUpdateIdentityProviderWithResponse Create or update an identity provider
//
// Idempotent create-or-update. Uses the key field in the body to identify the identity provider within the domain. On first apply the identity provider is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the identity provider.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities (the `AutomationCreateOrUpdateIdentityProvider` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, body AutomationCreateOrUpdateIdentityProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateIdentityProviderResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateIdentityProvider(ctx, orgId, envId, domainKey, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateIdentityProviderResponse(rsp)
}

// AutomationDeleteIdentityProviderWithResponse Delete an identity provider
//
// Deletes an Automation-managed identity provider by its key. Deleting an identity provider that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationDeleteIdentityProvider` operationId).
func (c *ClientWithResponses) AutomationDeleteIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteIdentityProviderResponse, error) {
	rsp, err := c.AutomationDeleteIdentityProvider(ctx, orgId, envId, domainKey, identityKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationDeleteIdentityProviderResponse(rsp)
}

// AutomationGetIdentityProviderWithResponse Get an identity provider
//
// Retrieves a single Automation-managed identity provider by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /organizations/{orgId}/environments/{envId}/domains/{domainKey}/identities/{identityKey} (the `AutomationGetIdentityProvider` operationId).
func (c *ClientWithResponses) AutomationGetIdentityProviderWithResponse(ctx context.Context, orgId string, envId string, domainKey string, identityKey string, reqEditors ...RequestEditorFn) (*AutomationGetIdentityProviderResponse, error) {
	rsp, err := c.AutomationGetIdentityProvider(ctx, orgId, envId, domainKey, identityKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationGetIdentityProviderResponse(rsp)
}

// ParseAutomationListIdentityProvidersResponse parses an HTTP response from a AutomationListIdentityProvidersWithResponse call
func ParseAutomationListIdentityProvidersResponse(rsp *http.Response) (*AutomationListIdentityProvidersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationListIdentityProvidersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationCreateOrUpdateIdentityProviderResponse parses an HTTP response from a AutomationCreateOrUpdateIdentityProviderWithResponse call
func ParseAutomationCreateOrUpdateIdentityProviderResponse(rsp *http.Response) (*AutomationCreateOrUpdateIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationCreateOrUpdateIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationDeleteIdentityProviderResponse parses an HTTP response from a AutomationDeleteIdentityProviderWithResponse call
func ParseAutomationDeleteIdentityProviderResponse(rsp *http.Response) (*AutomationDeleteIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationDeleteIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAutomationGetIdentityProviderResponse parses an HTTP response from a AutomationGetIdentityProviderWithResponse call
func ParseAutomationGetIdentityProviderResponse(rsp *http.Response) (*AutomationGetIdentityProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationGetIdentityProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationIdentityProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
