// Package reporter provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package reporter

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ScopedServerURLBaseUrlVariable is the `baseUrl` variable for ScopedServerURL
type ScopedServerURLBaseUrlVariable string

// ScopedServerURLBaseUrlVariableDefault is the default value for the `baseUrl` variable for ScopedServerURL
const ScopedServerURLBaseUrlVariableDefault = "http://localhost:8093/automation"

// ScopedServerURLEnvIdVariable is the `envId` variable for ScopedServerURL
type ScopedServerURLEnvIdVariable string

// ScopedServerURLEnvIdVariableDefault is the default value for the `envId` variable for ScopedServerURL
const ScopedServerURLEnvIdVariableDefault = "DEFAULT"

// ScopedServerURLOrgIdVariable is the `orgId` variable for ScopedServerURL
type ScopedServerURLOrgIdVariable string

// ScopedServerURLOrgIdVariableDefault is the default value for the `orgId` variable for ScopedServerURL
const ScopedServerURLOrgIdVariableDefault = "DEFAULT"

// NewScopedServerURL constructs the Server URL for Organization and environment scoped Automation API, with the provided variables.
func NewScopedServerURL(baseUrl ScopedServerURLBaseUrlVariable, envId ScopedServerURLEnvIdVariable, orgId ScopedServerURLOrgIdVariable) (string, error) {

	u := "{baseUrl}/organizations/{orgId}/environments/{envId}"

	u = strings.ReplaceAll(u, "{baseUrl}", string(baseUrl))
	u = strings.ReplaceAll(u, "{envId}", string(envId))
	u = strings.ReplaceAll(u, "{orgId}", string(orgId))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// AutomationReporter A reporter managed under a domain by the Automation API. Reporters persist audit events to a backend. The key field is the stable, immutable identity used for idempotent create-or-update.
type AutomationReporter struct {
	// AttributeMappings Additional attributes exported alongside the regular audit payload. Each entry pairs an expression read from the audit context with the field name its value is exported under. Ignored when system is true; a system reporter exports no additional attributes.
	AttributeMappings *[]ReporterAttributeMapping `json:"attributeMappings,omitempty"`

	// Configuration Plugin-specific configuration as a JSON-encoded string. Its shape is defined by the selected reporter type.
	//
	// Example: {"bootstrapServers":"kafka:9092","topic":"audit"}
	Configuration *string `json:"configuration,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DataType Category of data the reporter handles, derived from its type. Read-only.
	DataType *string `json:"dataType,omitempty"`

	// Enabled Whether the reporter is enabled.
	Enabled *bool `json:"enabled,omitempty"`

	// Key Stable, immutable identifier for the reporter within its domain. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the reporter on create-or-update.
	//
	// Example: audit-kafka
	Key string `json:"key"`

	// Name Human-readable name of the reporter.
	//
	// Example: Audit events to Kafka
	Name *string `json:"name,omitempty"`

	// System Whether this is the domain's system reporter. Immutable after creation. When true, only key is required; the reporter is built from the domains.reporters.default.* and repository system settings and the name, type, configuration, and attributeMappings fields are ignored.
	System *bool `json:"system,omitempty"`

	// Type Reporter plugin type identifier. Immutable after creation.
	//
	// Example: reporter-am-kafka
	Type *string `json:"type,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// ReporterAttributeMapping Exports one additional attribute, read from the audit context by expression, under a chosen field name.
type ReporterAttributeMapping struct {
	// ExportedName The name the evaluated value takes on the exported payload.
	//
	// Example: user_sub
	ExportedName *string `json:"exportedName,omitempty"`

	// Expression Expression evaluated against the audit context.
	//
	// Example: {#context.attributes['user'].additionalInformation['sub']}
	Expression *string `json:"expression,omitempty"`
}

// AutomationCreateOrUpdateReporterJSONRequestBody defines body for AutomationCreateOrUpdateReporter for application/json ContentType.
type AutomationCreateOrUpdateReporterJSONRequestBody = AutomationReporter

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// AutomationListReporters List a domain's reporters
	//
	// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
	//
	// Corresponds with GET /domains/{domainKey}/reporters (the `AutomationListReporters` operationId).
	AutomationListReporters(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateReporterWithBody Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
	AutomationCreateOrUpdateReporterWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationCreateOrUpdateReporter Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
	AutomationCreateOrUpdateReporter(ctx context.Context, domainKey string, body AutomationCreateOrUpdateReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationDeleteReporter Delete a reporter
	//
	// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
	//
	// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `AutomationDeleteReporter` operationId).
	AutomationDeleteReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AutomationGetReporter Get a reporter
	//
	// Retrieves a single Automation-managed reporter by its key.
	//
	// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `AutomationGetReporter` operationId).
	AutomationGetReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// AutomationListReporters List a domain's reporters
//
// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
//
// Corresponds with GET /domains/{domainKey}/reporters (the `AutomationListReporters` operationId).
func (c *Client) AutomationListReporters(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationListReportersRequest(c.Server, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateReporterWithBody Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
func (c *Client) AutomationCreateOrUpdateReporterWithBody(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateReporterRequestWithBody(c.Server, domainKey, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationCreateOrUpdateReporter Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
func (c *Client) AutomationCreateOrUpdateReporter(ctx context.Context, domainKey string, body AutomationCreateOrUpdateReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationCreateOrUpdateReporterRequest(c.Server, domainKey, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationDeleteReporter Delete a reporter
//
// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
//
// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `AutomationDeleteReporter` operationId).
func (c *Client) AutomationDeleteReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationDeleteReporterRequest(c.Server, domainKey, reporterKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AutomationGetReporter Get a reporter
//
// Retrieves a single Automation-managed reporter by its key.
//
// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `AutomationGetReporter` operationId).
func (c *Client) AutomationGetReporter(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAutomationGetReporterRequest(c.Server, domainKey, reporterKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewAutomationListReportersRequest constructs an http.Request for the AutomationListReporters method
func NewAutomationListReportersRequest(server string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationCreateOrUpdateReporterRequest calls the generic AutomationCreateOrUpdateReporter builder with application/json body
func NewAutomationCreateOrUpdateReporterRequest(server string, domainKey string, body AutomationCreateOrUpdateReporterJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAutomationCreateOrUpdateReporterRequestWithBody(server, domainKey, "application/json", bodyReader)
}

// NewAutomationCreateOrUpdateReporterRequestWithBody constructs an http.Request for the AutomationCreateOrUpdateReporter method, with any body, and a specified content type
func NewAutomationCreateOrUpdateReporterRequestWithBody(server string, domainKey string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewAutomationDeleteReporterRequest constructs an http.Request for the AutomationDeleteReporter method
func NewAutomationDeleteReporterRequest(server string, domainKey string, reporterKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "reporterKey", reporterKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAutomationGetReporterRequest constructs an http.Request for the AutomationGetReporter method
func NewAutomationGetReporterRequest(server string, domainKey string, reporterKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "reporterKey", reporterKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s/reporters/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// AutomationListReportersWithResponse List a domain's reporters
	//
	// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/reporters (the `AutomationListReporters` operationId).
	AutomationListReportersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListReportersResponse, error)

	// AutomationCreateOrUpdateReporterWithBodyWithResponse Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
	AutomationCreateOrUpdateReporterWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateReporterResponse, error)

	// AutomationCreateOrUpdateReporterWithResponse Create or update a reporter
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
	AutomationCreateOrUpdateReporterWithResponse(ctx context.Context, domainKey string, body AutomationCreateOrUpdateReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateReporterResponse, error)

	// AutomationDeleteReporterWithResponse Delete a reporter
	//
	// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `AutomationDeleteReporter` operationId).
	AutomationDeleteReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteReporterResponse, error)

	// AutomationGetReporterWithResponse Get a reporter
	//
	// Retrieves a single Automation-managed reporter by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `AutomationGetReporter` operationId).
	AutomationGetReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*AutomationGetReporterResponse, error)
}

type AutomationListReportersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationReporter
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationListReportersResponse) GetJSON200() *[]AutomationReporter {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationListReportersResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationListReportersResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationListReportersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationListReportersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationListReportersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationListReportersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationCreateOrUpdateReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationReporter
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationCreateOrUpdateReporterResponse) GetJSON200() *AutomationReporter {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r AutomationCreateOrUpdateReporterResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationCreateOrUpdateReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationCreateOrUpdateReporterResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationCreateOrUpdateReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationCreateOrUpdateReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationCreateOrUpdateReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationCreateOrUpdateReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationDeleteReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationDeleteReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r AutomationDeleteReporterResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r AutomationDeleteReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationDeleteReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationDeleteReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationDeleteReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AutomationGetReporterResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationReporter
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AutomationGetReporterResponse) GetJSON200() *AutomationReporter {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r AutomationGetReporterResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r AutomationGetReporterResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r AutomationGetReporterResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AutomationGetReporterResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AutomationGetReporterResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AutomationGetReporterResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// AutomationListReportersWithResponse List a domain's reporters
//
// Returns all reporters managed by the Automation API under the domain. Reporters created outside the Automation API are not returned.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/reporters (the `AutomationListReporters` operationId).
func (c *ClientWithResponses) AutomationListReportersWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*AutomationListReportersResponse, error) {
	rsp, err := c.AutomationListReporters(ctx, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationListReportersResponse(rsp)
}

// AutomationCreateOrUpdateReporterWithBodyWithResponse Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateReporterWithBodyWithResponse(ctx context.Context, domainKey string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateReporterResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateReporterWithBody(ctx, domainKey, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateReporterResponse(rsp)
}

// AutomationCreateOrUpdateReporterWithResponse Create or update a reporter
//
// Idempotent create-or-update. Uses the key field in the body to identify the reporter within the domain. On first apply the reporter is created; subsequent applies update it. The system flag is immutable; changing it requires deleting and recreating the reporter.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains/{domainKey}/reporters (the `AutomationCreateOrUpdateReporter` operationId).
func (c *ClientWithResponses) AutomationCreateOrUpdateReporterWithResponse(ctx context.Context, domainKey string, body AutomationCreateOrUpdateReporterJSONRequestBody, reqEditors ...RequestEditorFn) (*AutomationCreateOrUpdateReporterResponse, error) {
	rsp, err := c.AutomationCreateOrUpdateReporter(ctx, domainKey, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationCreateOrUpdateReporterResponse(rsp)
}

// AutomationDeleteReporterWithResponse Delete a reporter
//
// Deletes an Automation-managed reporter by its key. Deleting a reporter that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /domains/{domainKey}/reporters/{reporterKey} (the `AutomationDeleteReporter` operationId).
func (c *ClientWithResponses) AutomationDeleteReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*AutomationDeleteReporterResponse, error) {
	rsp, err := c.AutomationDeleteReporter(ctx, domainKey, reporterKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationDeleteReporterResponse(rsp)
}

// AutomationGetReporterWithResponse Get a reporter
//
// Retrieves a single Automation-managed reporter by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey}/reporters/{reporterKey} (the `AutomationGetReporter` operationId).
func (c *ClientWithResponses) AutomationGetReporterWithResponse(ctx context.Context, domainKey string, reporterKey string, reqEditors ...RequestEditorFn) (*AutomationGetReporterResponse, error) {
	rsp, err := c.AutomationGetReporter(ctx, domainKey, reporterKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAutomationGetReporterResponse(rsp)
}

// ParseAutomationListReportersResponse parses an HTTP response from a AutomationListReportersWithResponse call
func ParseAutomationListReportersResponse(rsp *http.Response) (*AutomationListReportersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationListReportersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationCreateOrUpdateReporterResponse parses an HTTP response from a AutomationCreateOrUpdateReporterWithResponse call
func ParseAutomationCreateOrUpdateReporterResponse(rsp *http.Response) (*AutomationCreateOrUpdateReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationCreateOrUpdateReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseAutomationDeleteReporterResponse parses an HTTP response from a AutomationDeleteReporterWithResponse call
func ParseAutomationDeleteReporterResponse(rsp *http.Response) (*AutomationDeleteReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationDeleteReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseAutomationGetReporterResponse parses an HTTP response from a AutomationGetReporterWithResponse call
func ParseAutomationGetReporterResponse(rsp *http.Response) (*AutomationGetReporterResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AutomationGetReporterResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationReporter
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
