// Package domain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package domain

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// ScopedServerURLBaseUrlVariable is the `baseUrl` variable for ScopedServerURL
type ScopedServerURLBaseUrlVariable string

// ScopedServerURLBaseUrlVariableDefault is the default value for the `baseUrl` variable for ScopedServerURL
const ScopedServerURLBaseUrlVariableDefault = "http://localhost:8093/automation"

// ScopedServerURLEnvIdVariable is the `envId` variable for ScopedServerURL
type ScopedServerURLEnvIdVariable string

// ScopedServerURLEnvIdVariableDefault is the default value for the `envId` variable for ScopedServerURL
const ScopedServerURLEnvIdVariableDefault = "DEFAULT"

// ScopedServerURLOrgIdVariable is the `orgId` variable for ScopedServerURL
type ScopedServerURLOrgIdVariable string

// ScopedServerURLOrgIdVariableDefault is the default value for the `orgId` variable for ScopedServerURL
const ScopedServerURLOrgIdVariableDefault = "DEFAULT"

// NewScopedServerURL constructs the Server URL for Organization and environment scoped Automation API, with the provided variables.
func NewScopedServerURL(baseUrl ScopedServerURLBaseUrlVariable, envId ScopedServerURLEnvIdVariable, orgId ScopedServerURLOrgIdVariable) (string, error) {

	u := "{baseUrl}/organizations/{orgId}/environments/{envId}"

	u = strings.ReplaceAll(u, "{baseUrl}", string(baseUrl))
	u = strings.ReplaceAll(u, "{envId}", string(envId))
	u = strings.ReplaceAll(u, "{orgId}", string(orgId))

	if strings.Contains(u, "{") || strings.Contains(u, "}") {
		return "", fmt.Errorf("after mapping variables, there were still `{` or `}` characters in the string: %#v", u)
	}

	return u, nil
}

// Defines values for TokenExchangeClaimMappingSource.
const (
	ActorToken   TokenExchangeClaimMappingSource = "actor_token"
	SubjectToken TokenExchangeClaimMappingSource = "subject_token"
)

// Valid indicates whether the value is a known member of the TokenExchangeClaimMappingSource enum.
func (e TokenExchangeClaimMappingSource) Valid() bool {
	switch e {
	case ActorToken:
		return true
	case SubjectToken:
		return true
	default:
		return false
	}
}

// Defines values for TokenExchangeOAuthSettingsScopeHandling.
const (
	Downscoping TokenExchangeOAuthSettingsScopeHandling = "downscoping"
	Permissive  TokenExchangeOAuthSettingsScopeHandling = "permissive"
)

// Valid indicates whether the value is a known member of the TokenExchangeOAuthSettingsScopeHandling enum.
func (e TokenExchangeOAuthSettingsScopeHandling) Valid() bool {
	switch e {
	case Downscoping:
		return true
	case Permissive:
		return true
	default:
		return false
	}
}

// Defines values for TrustedIssuerKeyResolutionMethod.
const (
	JwksUrl TrustedIssuerKeyResolutionMethod = "jwks_url"
	Pem     TrustedIssuerKeyResolutionMethod = "pem"
)

// Valid indicates whether the value is a known member of the TrustedIssuerKeyResolutionMethod enum.
func (e TrustedIssuerKeyResolutionMethod) Valid() bool {
	switch e {
	case JwksUrl:
		return true
	case Pem:
		return true
	default:
		return false
	}
}

// Defines values for WebAuthnSettingsAttestationConveyancePreference.
const (
	Direct   WebAuthnSettingsAttestationConveyancePreference = "direct"
	Indirect WebAuthnSettingsAttestationConveyancePreference = "indirect"
	None     WebAuthnSettingsAttestationConveyancePreference = "none"
)

// Valid indicates whether the value is a known member of the WebAuthnSettingsAttestationConveyancePreference enum.
func (e WebAuthnSettingsAttestationConveyancePreference) Valid() bool {
	switch e {
	case Direct:
		return true
	case Indirect:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for WebAuthnSettingsAuthenticatorAttachment.
const (
	CrossPlatform WebAuthnSettingsAuthenticatorAttachment = "cross_platform"
	Platform      WebAuthnSettingsAuthenticatorAttachment = "platform"
)

// Valid indicates whether the value is a known member of the WebAuthnSettingsAuthenticatorAttachment enum.
func (e WebAuthnSettingsAuthenticatorAttachment) Valid() bool {
	switch e {
	case CrossPlatform:
		return true
	case Platform:
		return true
	default:
		return false
	}
}

// Defines values for WebAuthnSettingsUserVerification.
const (
	Discouraged WebAuthnSettingsUserVerification = "discouraged"
	Preferred   WebAuthnSettingsUserVerification = "preferred"
	Required    WebAuthnSettingsUserVerification = "required"
)

// Valid indicates whether the value is a known member of the WebAuthnSettingsUserVerification enum.
func (e WebAuthnSettingsUserVerification) Valid() bool {
	switch e {
	case Discouraged:
		return true
	case Preferred:
		return true
	case Required:
		return true
	default:
		return false
	}
}

// AutomationAccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
type AutomationAccountSettings = AccountSettings

// AccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
type AccountSettings struct {
	// AccountBlockedDuration Duration, in seconds, for which the account remains blocked after too many failed login attempts.
	//
	// Example: 7200
	AccountBlockedDuration *int32 `json:"accountBlockedDuration,omitempty"`

	// AutoLoginAfterRegistration Whether the user is automatically logged in after completing registration.
	AutoLoginAfterRegistration *bool `json:"autoLoginAfterRegistration,omitempty"`

	// AutoLoginAfterResetPassword Whether the user is automatically logged in after a password reset.
	AutoLoginAfterResetPassword *bool `json:"autoLoginAfterResetPassword,omitempty"`

	// CompleteRegistrationWhenResetPassword Whether resetting a password also completes a pending registration.
	CompleteRegistrationWhenResetPassword *bool `json:"completeRegistrationWhenResetPassword,omitempty"`

	// DefaultIdentityProviderForRegistration Key of an identity provider that exists under this domain, used as the default for user registration. Resolved against the domain's identity providers when applied; a value that does not match an existing identity provider is rejected with a 400 response.
	//
	// Example: users-idp
	DefaultIdentityProviderForRegistration *string `json:"defaultIdentityProviderForRegistration,omitempty"`

	// DeletePasswordlessDevicesAfterResetPassword Whether passwordless (WebAuthn) devices are deleted when the password is reset.
	DeletePasswordlessDevicesAfterResetPassword *bool `json:"deletePasswordlessDevicesAfterResetPassword,omitempty"`

	// DynamicUserRegistration Whether dynamic (self-service) user registration is enabled.
	DynamicUserRegistration *bool `json:"dynamicUserRegistration,omitempty"`

	// Inherited Whether account settings are inherited from the parent (domain). When true, the other fields are ignored. Has no effect when applied to domains.
	Inherited *bool `json:"inherited,omitempty"`

	// LoginAttemptsDetectionEnabled Whether brute-force authentication attempts are detected and blocked.
	LoginAttemptsDetectionEnabled *bool `json:"loginAttemptsDetectionEnabled,omitempty"`

	// LoginAttemptsResetTime Time, in seconds, after which the login attempt counter is reset when the maximum has not been reached.
	//
	// Example: 600
	LoginAttemptsResetTime *int32 `json:"loginAttemptsResetTime,omitempty"`

	// MaxLoginAttempts Maximum number of failed login attempts before the account is blocked.
	//
	// Example: 10
	MaxLoginAttempts *int32 `json:"maxLoginAttempts,omitempty"`

	// MfaChallengeAttemptsDetectionEnabled Whether failed MFA challenge attempts are detected and blocked.
	MfaChallengeAttemptsDetectionEnabled *bool `json:"mfaChallengeAttemptsDetectionEnabled,omitempty"`

	// MfaChallengeAttemptsResetTime Time, in seconds, after which the MFA challenge attempt counter is reset.
	//
	// Example: 600
	MfaChallengeAttemptsResetTime *int32 `json:"mfaChallengeAttemptsResetTime,omitempty"`

	// MfaChallengeMaxAttempts Maximum number of failed MFA challenge attempts before the user is blocked.
	//
	// Example: 3
	MfaChallengeMaxAttempts *int32 `json:"mfaChallengeMaxAttempts,omitempty"`

	// MfaChallengeSendVerifyAlertEmail Whether to send an alert email after too many failed MFA challenge attempts.
	MfaChallengeSendVerifyAlertEmail *bool `json:"mfaChallengeSendVerifyAlertEmail,omitempty"`

	// RedirectUriAfterRegistration URL the user is redirected to after registration.
	//
	// Example: https://app.example.com/welcome
	RedirectUriAfterRegistration *string `json:"redirectUriAfterRegistration,omitempty"`

	// RedirectUriAfterResetPassword URL the user is redirected to after a password reset.
	//
	// Example: https://app.example.com/signin
	RedirectUriAfterResetPassword *string `json:"redirectUriAfterResetPassword,omitempty"`

	// RememberMe Whether users can remain logged in for a fixed duration (remember-me).
	RememberMe *bool `json:"rememberMe,omitempty"`

	// RememberMeDuration Duration, in seconds, for which a remembered session stays valid.
	//
	// Example: 604800
	RememberMeDuration *int32 `json:"rememberMeDuration,omitempty"`

	// ResetPasswordConfirmIdentity Whether the user must confirm their identity before resetting a password.
	ResetPasswordConfirmIdentity *bool `json:"resetPasswordConfirmIdentity,omitempty"`

	// ResetPasswordCustomForm Whether a custom form is used for the password-reset step.
	ResetPasswordCustomForm *bool `json:"resetPasswordCustomForm,omitempty"`

	// ResetPasswordCustomFormFields Custom fields rendered on the password-reset form.
	ResetPasswordCustomFormFields *[]FormField `json:"resetPasswordCustomFormFields,omitempty"`

	// ResetPasswordInvalidateTokens Whether existing tokens are invalidated when the password is reset.
	ResetPasswordInvalidateTokens *bool `json:"resetPasswordInvalidateTokens,omitempty"`

	// SendRecoverAccountEmail Whether to send an account-recovery email.
	SendRecoverAccountEmail *bool `json:"sendRecoverAccountEmail,omitempty"`

	// SendVerifyRegistrationAccountEmail Whether to send a registration-verification email.
	SendVerifyRegistrationAccountEmail *bool `json:"sendVerifyRegistrationAccountEmail,omitempty"`
}

// AutomationCIBASettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
type AutomationCIBASettings = CIBASettings

// CIBASettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
type CIBASettings struct {
	// AuthReqExpiry Default validity period, in seconds, of the issued auth_req_id.
	//
	// Example: 600
	AuthReqExpiry *int32 `json:"authReqExpiry,omitempty"`

	// BindingMessageLength Maximum number of characters accepted for the binding_message parameter.
	//
	// Example: 256
	BindingMessageLength *int32 `json:"bindingMessageLength,omitempty"`

	// Enabled Whether Client-Initiated Backchannel Authentication is enabled for the domain.
	Enabled *bool `json:"enabled,omitempty"`

	// TokenReqInterval Minimum delay, in seconds, that a client must wait between two polls of the token endpoint for the same auth_req_id (POLL or PING delivery mode).
	//
	// Example: 5
	TokenReqInterval *int32 `json:"tokenReqInterval,omitempty"`
}

// AutomationCertificateSettings Domain-level certificate settings.
type AutomationCertificateSettings = CertificateSettings

// CertificateSettings Domain-level certificate settings.
type CertificateSettings struct {
	// FallbackCertificate Key of a certificate managed under this domain, used as the fallback certificate when a client does not specify one. Must reference a certificate created via the domain's certificate endpoints.
	//
	// Example: default
	FallbackCertificate *string `json:"fallbackCertificate,omitempty"`
}

// AutomationClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
type AutomationClientRegistrationSettings = ClientRegistrationSettings

// ClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
type ClientRegistrationSettings struct {
	// AllowHttpSchemeRedirectUri Whether the unsecured http scheme is permitted in redirect URIs.
	AllowHttpSchemeRedirectUri *bool `json:"allowHttpSchemeRedirectUri,omitempty"`

	// AllowLocalhostRedirectUri Whether localhost is permitted as a redirect URI host.
	AllowLocalhostRedirectUri *bool `json:"allowLocalhostRedirectUri,omitempty"`

	// AllowRedirectUriParamsExpressionLanguage Whether expression language is permitted in redirect URI parameters.
	AllowRedirectUriParamsExpressionLanguage *bool `json:"allowRedirectUriParamsExpressionLanguage,omitempty"`

	// AllowWildCardRedirectUri Whether wildcards are permitted in redirect URIs.
	AllowWildCardRedirectUri *bool `json:"allowWildCardRedirectUri,omitempty"`

	// AllowedScopes Scopes permitted on client registration requests when the allowed list is enabled.
	AllowedScopes *[]string `json:"allowedScopes,omitempty"`

	// AllowedScopesEnabled Whether registered client scopes are restricted to an allowed list.
	AllowedScopesEnabled *bool `json:"allowedScopesEnabled,omitempty"`

	// ClientTemplateEnabled Whether a client may be used as a template for dynamic client registration.
	ClientTemplateEnabled *bool `json:"clientTemplateEnabled,omitempty"`

	// DefaultScopes Default scopes added to every client registration request.
	DefaultScopes *[]string `json:"defaultScopes,omitempty"`

	// DynamicClientRegistrationEnabled Whether Dynamic Client Registration is enabled for the domain.
	DynamicClientRegistrationEnabled *bool `json:"dynamicClientRegistrationEnabled,omitempty"`

	// OpenDynamicClientRegistrationEnabled Whether open (unauthenticated) Dynamic Client Registration is enabled for the domain.
	OpenDynamicClientRegistrationEnabled *bool `json:"openDynamicClientRegistrationEnabled,omitempty"`
}

// AutomationDomain A security domain managed by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update. Certificates, identity providers, and reporters are not embedded; they are managed via the domain's sub-resource endpoints and referenced here by key.
type AutomationDomain = Domain

// Domain A security domain managed by the Automation API. The key field is the stable, immutable identity used for idempotent create-or-update. Certificates, identity providers, and reporters are not embedded; they are managed via the domain's sub-resource endpoints and referenced here by key.
type Domain struct {
	// AccountSettings User account settings for the domain: brute-force protection, registration, password reset, remember-me, and MFA challenge behavior.
	AccountSettings *AutomationAccountSettings `json:"accountSettings,omitempty"`

	// AlertEnabled Whether alerting is enabled for the domain.
	AlertEnabled *bool `json:"alertEnabled,omitempty"`

	// CertificateSettings Domain-level certificate settings.
	CertificateSettings *AutomationCertificateSettings `json:"certificateSettings,omitempty"`

	// CorsSettings Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
	CorsSettings *CorsSettings `json:"corsSettings,omitempty"`

	// CreatedAt Creation timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	CreatedAt *time.Time `json:"createdAt,omitempty"`

	// DataPlaneId Identifier of the data plane this domain is connected to. Optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards; included in the desired-state document but never re-applied on update.
	//
	// Example: default
	DataPlaneId *string `json:"dataPlaneId,omitempty"`

	// Description Human-readable description of the domain.
	//
	// Example: An example authentication domain
	Description *string `json:"description,omitempty"`

	// Enabled Whether the domain handles incoming authentication and authorization requests.
	Enabled *bool `json:"enabled,omitempty"`

	// Key Stable, immutable identifier for the domain within its environment. Lowercase alphanumeric and hyphens, starting and ending with an alphanumeric character. Used to identify the domain on create-or-update.
	//
	// Example: example-domain
	Key string `json:"key"`

	// LoginSettings Configuration of the domain's login flow and the features offered on the sign-in page.
	LoginSettings *LoginSettings `json:"loginSettings,omitempty"`

	// Master Whether this is the master domain of its environment. A master domain may perform cross-domain token introspection.
	Master *bool `json:"master,omitempty"`

	// Name Human-readable name of the domain.
	//
	// Example: Example domain
	Name string `json:"name"`

	// Oidc OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
	Oidc *AutomationOidcSettings `json:"oidc,omitempty"`

	// PasswordSettings Password policy applied to users of the domain: complexity requirements, expiry, and history.
	PasswordSettings *PasswordSettings `json:"passwordSettings,omitempty"`

	// Path Context path the domain is served under, relative to the gateway. Must start with a slash.
	//
	// Example: /example-domain
	Path string `json:"path"`

	// Saml Settings for the domain acting as a SAML 2.0 identity provider (IdP).
	Saml *AutomationSamlSettings `json:"saml,omitempty"`

	// Scim Configuration of the domain's SCIM 2.0 provisioning endpoints.
	Scim *SCIMSettings `json:"scim,omitempty"`

	// SecretExpirationSettings Controls whether client secrets in the domain expire and after how long.
	SecretExpirationSettings *SecretExpirationSettings `json:"secretExpirationSettings,omitempty"`

	// SelfServiceAccountManagementSettings Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
	SelfServiceAccountManagementSettings *SelfServiceAccountManagementSettings `json:"selfServiceAccountManagementSettings,omitempty"`

	// Tags Sharding tags that control which gateways deploy this domain.
	//
	// Example: ["eu","production"]
	Tags *[]string `json:"tags,omitempty"`

	// TokenExchangeSettings OAuth 2.0 Token Exchange (RFC 8693) configuration for the domain, covering impersonation and delegation.
	TokenExchangeSettings *TokenExchangeSettings `json:"tokenExchangeSettings,omitempty"`

	// Uma Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
	Uma *UMASettings `json:"uma,omitempty"`

	// UpdatedAt Last-update timestamp (ISO-8601 / RFC 3339, UTC). Read-only.
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`

	// VhostMode Whether the domain is exposed through its virtual hosts rather than the default context path. When true, vhosts must be supplied.
	VhostMode *bool `json:"vhostMode,omitempty"`

	// Vhosts Virtual hosts the domain is exposed on, overriding the default context path.
	Vhosts *[]VirtualHost `json:"vhosts,omitempty"`

	// WebAuthnSettings WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
	WebAuthnSettings *WebAuthnSettings `json:"webAuthnSettings,omitempty"`

	// WebProtectionSettings HTTP security headers applied to the domain's login and consent pages.
	WebProtectionSettings *WebProtectionSettings `json:"webProtectionSettings,omitempty"`
}

// AutomationOidcSettings OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
type AutomationOidcSettings = OidcSettings

// OidcSettings OpenID Connect settings for the domain. CIMD (client identity metadata document) settings are not exposed by the Automation API and are reset on update.
type OidcSettings struct {
	// CibaSettings Client-Initiated Backchannel Authentication (CIBA) settings for the domain. CIBA lets a relying party initiate end-user authentication from a separate consumption device, without redirecting the user through the browser. Authentication device notifiers are not managed by the Automation API and are not exposed here.
	CibaSettings *AutomationCIBASettings `json:"cibaSettings,omitempty"`

	// ClientRegistrationSettings OpenID Connect Dynamic Client Registration configuration for the domain.
	ClientRegistrationSettings *AutomationClientRegistrationSettings `json:"clientRegistrationSettings,omitempty"`

	// PostLogoutRedirectUris URLs the user may be redirected to after sign-out (post_logout_redirect_uri).
	PostLogoutRedirectUris *[]string `json:"postLogoutRedirectUris,omitempty"`

	// RedirectUriStrictMatching Whether redirect_uri and post_logout_redirect_uri values are matched strictly during OpenID Connect flows.
	RedirectUriStrictMatching *bool `json:"redirectUriStrictMatching,omitempty"`

	// RequestUris Allowed request_uri values for passing OpenID Connect request objects by reference.
	RequestUris *[]string `json:"requestUris,omitempty"`

	// SecurityProfileSettings Financial-grade API (FAPI) security profile configuration for the domain.
	SecurityProfileSettings *SecurityProfileSettings `json:"securityProfileSettings,omitempty"`

	// WorkloadIdentitySettings Workload identity (SPIFFE) settings for the domain.
	WorkloadIdentitySettings *SpiffeDomainSettings `json:"workloadIdentitySettings,omitempty"`
}

// AutomationSamlSettings Settings for the domain acting as a SAML 2.0 identity provider (IdP).
type AutomationSamlSettings = SamlSettings

// SamlSettings Settings for the domain acting as a SAML 2.0 identity provider (IdP).
type SamlSettings struct {
	// Certificate Key of a certificate managed under this domain, used to sign SAML responses. Must reference a certificate created via the domain's certificate endpoints.
	//
	// Example: signing-cert
	Certificate *string `json:"certificate,omitempty"`

	// Enabled Whether the domain exposes the SAML 2.0 IdP protocol.
	Enabled *bool `json:"enabled,omitempty"`

	// EntityId URL or URN that uniquely identifies this IdP (the SAML entity ID).
	//
	// Example: https://auth.example.com/saml2/idp/entity
	EntityId *string `json:"entityId,omitempty"`
}

// CorsSettings Cross-Origin Resource Sharing configuration controlling which web origins may call the domain's endpoints from a browser.
type CorsSettings struct {
	// AllowCredentials Whether the browser may send credentials (cookies, authorization headers) with cross-origin requests.
	AllowCredentials *bool `json:"allowCredentials,omitempty"`

	// AllowedHeaders Request headers permitted on cross-origin requests.
	//
	// Example: ["Authorization","Content-Type"]
	AllowedHeaders *[]string `json:"allowedHeaders,omitempty"`

	// AllowedMethods HTTP methods permitted on cross-origin requests.
	//
	// Example: ["GET","POST","PUT","DELETE"]
	AllowedMethods *[]string `json:"allowedMethods,omitempty"`

	// AllowedOrigins Origins permitted to make cross-origin requests. Use "*" to allow any origin.
	//
	// Example: ["https://app.example.com"]
	AllowedOrigins *[]string `json:"allowedOrigins,omitempty"`

	// Enabled Whether CORS handling is enabled for the domain when not inherited.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether CORS settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `json:"inherited,omitempty"`

	// MaxAge How long, in seconds, a browser may cache the result of a preflight request.
	MaxAge *int32 `json:"maxAge,omitempty"`
}

// CspSettings Content Security Policy configuration for the domain's login and consent pages.
type CspSettings struct {
	// Directives CSP directives, one per entry, in the form "directive-name value". A trailing semicolon is optional. Directive names must be valid CSP tokens and must not repeat; values are not interpreted. Directives that take no value, such as "upgrade-insecure-requests", may be supplied on their own. When reportOnly is enabled, a "report-uri" or "report-to" directive is required.
	//
	// Example: ["default-src 'self'","script-src 'self'","upgrade-insecure-requests"]
	Directives *[]string `json:"directives,omitempty"`

	// Enabled Whether CSP is enabled for the domain when not inherited.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether CSP settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `json:"inherited,omitempty"`

	// ReportOnly When true, the policy is delivered as Content-Security-Policy-Report-Only.
	ReportOnly *bool `json:"reportOnly,omitempty"`

	// ScriptInlineNonce Whether inline scripts are allowed via a per-request nonce.
	ScriptInlineNonce *bool `json:"scriptInlineNonce,omitempty"`
}

// Error Error response body returned for failed requests.
type Error struct {
	// HttpStatus HTTP status code of the error response.
	//
	// Example: 400
	HttpStatus *int32 `json:"http_status,omitempty"`

	// Message Human-readable description of the error.
	Message *string `json:"message,omitempty"`
}

// FormField A single field shown on a user-facing form, such as registration.
type FormField struct {
	// Key Identifier of the field, mapped to a user attribute.
	//
	// Example: email
	Key *string `json:"key,omitempty"`

	// Label Label displayed for the field.
	//
	// Example: Email
	Label *string `json:"label,omitempty"`

	// Type Input type of the field.
	//
	// Example: email
	Type *string `json:"type,omitempty"`
}

// LoginSettings Configuration of the domain's login flow and the features offered on the sign-in page.
type LoginSettings struct {
	// CertificateBasedAuthEnabled Whether certificate-based authentication is offered.
	CertificateBasedAuthEnabled *bool `json:"certificateBasedAuthEnabled,omitempty"`

	// CertificateBasedAuthUrl URL used for certificate-based authentication.
	CertificateBasedAuthUrl *string `json:"certificateBasedAuthUrl,omitempty"`

	// ForgotPasswordEnabled Whether users can initiate a forgot-password flow from the login page.
	ForgotPasswordEnabled *bool `json:"forgotPasswordEnabled,omitempty"`

	// HideForm Whether the login form is hidden (for example when only social or identifier-first login is offered).
	HideForm *bool `json:"hideForm,omitempty"`

	// IdentifierFirstEnabled Whether identifier-first login is enabled, prompting for the username before the password.
	IdentifierFirstEnabled *bool `json:"identifierFirstEnabled,omitempty"`

	// Inherited Whether these login settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	Inherited *bool `json:"inherited,omitempty"`

	// MagicLinkAuthEnabled Whether magic-link authentication is offered.
	MagicLinkAuthEnabled *bool `json:"magicLinkAuthEnabled,omitempty"`

	// PasswordlessDeviceNamingEnabled Whether users can name their passwordless devices.
	PasswordlessDeviceNamingEnabled *bool `json:"passwordlessDeviceNamingEnabled,omitempty"`

	// PasswordlessEnabled Whether passwordless (WebAuthn) authentication is offered.
	PasswordlessEnabled *bool `json:"passwordlessEnabled,omitempty"`

	// PasswordlessEnforcePasswordEnabled Whether a password is still required alongside passwordless authentication.
	PasswordlessEnforcePasswordEnabled *bool `json:"passwordlessEnforcePasswordEnabled,omitempty"`

	// PasswordlessEnforcePasswordMaxAge Period, in seconds, after which the user's credentials must be re-entered to keep using passwordless authentication.
	PasswordlessEnforcePasswordMaxAge *int32 `json:"passwordlessEnforcePasswordMaxAge,omitempty"`

	// PasswordlessRememberDeviceEnabled Whether a passwordless device can be remembered to skip future challenges.
	PasswordlessRememberDeviceEnabled *bool `json:"passwordlessRememberDeviceEnabled,omitempty"`

	// RegisterEnabled Whether users can self-register from the login page.
	RegisterEnabled *bool `json:"registerEnabled,omitempty"`

	// RememberMeEnabled Whether the login page offers a remember-me option.
	RememberMeEnabled *bool `json:"rememberMeEnabled,omitempty"`

	// ResetPasswordOnExpiration Whether the user is forced to reset their password once it expires.
	ResetPasswordOnExpiration *bool `json:"resetPasswordOnExpiration,omitempty"`
}

// PasswordSettings Password policy applied to users of the domain: complexity requirements, expiry, and history.
type PasswordSettings struct {
	// ExcludePasswordsInDictionary Whether passwords found in a common-password dictionary are rejected.
	ExcludePasswordsInDictionary *bool `json:"excludePasswordsInDictionary,omitempty"`

	// ExcludeUserProfileInfoInPassword Whether passwords containing the user's profile information are rejected.
	ExcludeUserProfileInfoInPassword *bool `json:"excludeUserProfileInfoInPassword,omitempty"`

	// ExpiryDuration Number of days after which a password expires and must be changed.
	ExpiryDuration *int32 `json:"expiryDuration,omitempty"`

	// IncludeNumbers Whether a password must contain at least one number.
	IncludeNumbers *bool `json:"includeNumbers,omitempty"`

	// IncludeSpecialCharacters Whether a password must contain at least one special character.
	IncludeSpecialCharacters *bool `json:"includeSpecialCharacters,omitempty"`

	// Inherited Whether these password settings are inherited from a parent scope rather than defined here. When true, the other fields are ignored.
	Inherited *bool `json:"inherited,omitempty"`

	// LettersInMixedCase Whether a password must contain both uppercase and lowercase letters.
	LettersInMixedCase *bool `json:"lettersInMixedCase,omitempty"`

	// MaxConsecutiveLetters Maximum number of identical consecutive characters allowed in a password.
	MaxConsecutiveLetters *int32 `json:"maxConsecutiveLetters,omitempty"`

	// MaxLength Maximum number of characters a password may contain.
	MaxLength *int32 `json:"maxLength,omitempty"`

	// MinLength Minimum number of characters a password must contain.
	MinLength *int32 `json:"minLength,omitempty"`

	// OldPasswords Number of previous passwords retained in history and barred from reuse.
	OldPasswords *int32 `json:"oldPasswords,omitempty"`

	// PasswordHistoryEnabled Whether password history is enforced to prevent reuse of recent passwords.
	PasswordHistoryEnabled *bool `json:"passwordHistoryEnabled,omitempty"`
}

// ResetPasswordSettings Rules applied to a self-service password reset.
type ResetPasswordSettings struct {
	// OldPasswordRequired Whether the user must supply their current password to set a new one.
	OldPasswordRequired *bool `json:"oldPasswordRequired,omitempty"`

	// TokenAge Lifetime, in seconds, of the password-reset token.
	TokenAge *int32 `json:"tokenAge,omitempty"`
}

// SCIMSettings Configuration of the domain's SCIM 2.0 provisioning endpoints.
type SCIMSettings struct {
	// Enabled Whether the SCIM provisioning API is enabled for the domain.
	Enabled *bool `json:"enabled,omitempty"`

	// IdpSelectionEnabled Whether an identity provider is selected for SCIM-provisioned users using a selection rule.
	IdpSelectionEnabled *bool `json:"idpSelectionEnabled,omitempty"`

	// IdpSelectionRule Expression that selects the identity provider for a SCIM-provisioned user.
	IdpSelectionRule *string `json:"idpSelectionRule,omitempty"`
}

// SecretExpirationSettings Controls whether client secrets in the domain expire and after how long.
type SecretExpirationSettings struct {
	// Enabled Whether client-secret expiration is enabled.
	Enabled *bool `json:"enabled,omitempty"`

	// ExpiryTimeSeconds Lifetime, in seconds, of a client secret before it expires.
	//
	// Example: 7776000
	ExpiryTimeSeconds *int64 `json:"expiryTimeSeconds,omitempty"`
}

// SecurityProfileSettings Financial-grade API (FAPI) security profile configuration for the domain.
type SecurityProfileSettings struct {
	// EnableFapiBrazil Whether the Open Banking Brasil Financial-grade API security profile (version 1.0) is applied.
	EnableFapiBrazil *bool `json:"enableFapiBrazil,omitempty"`

	// EnablePlainFapi Whether the standard Financial-grade API security profile (version 1.0) is applied.
	EnablePlainFapi *bool `json:"enablePlainFapi,omitempty"`
}

// SelfServiceAccountManagementSettings Controls whether end users can manage their own account (for example, reset their password) and the rules that apply.
type SelfServiceAccountManagementSettings struct {
	// Enabled Whether self-service account management is enabled for end users.
	Enabled *bool `json:"enabled,omitempty"`

	// ResetPassword Rules applied to a self-service password reset.
	ResetPassword *ResetPasswordSettings `json:"resetPassword,omitempty"`
}

// SpiffeDomainSettings Workload identity (SPIFFE) settings for the domain.
type SpiffeDomainSettings struct {
	// AllowPrivateIpAddress Whether trust bundles can be fetched from private IP addresses.
	AllowPrivateIpAddress *bool `json:"allowPrivateIpAddress,omitempty"`

	// AllowUnsecuredHttpUri Whether trust bundles can be fetched over unsecured HTTP URIs.
	AllowUnsecuredHttpUri *bool `json:"allowUnsecuredHttpUri,omitempty"`

	// CacheMaxEntries Maximum number of trust bundle entries retained in the cache.
	CacheMaxEntries *int32 `json:"cacheMaxEntries,omitempty"`

	// CacheTtlSeconds Time-to-live, in seconds, for cached trust bundle entries.
	CacheTtlSeconds *int32 `json:"cacheTtlSeconds,omitempty"`

	// ClockSkewSeconds Allowed clock skew, in seconds, when validating JWT temporal claims.
	ClockSkewSeconds *int32 `json:"clockSkewSeconds,omitempty"`

	// DefaultAllowedAlgorithms Default allowlist of signature algorithms accepted for SPIFFE JWT validation.
	DefaultAllowedAlgorithms *[]string `json:"defaultAllowedAlgorithms,omitempty"`

	// Enabled Whether SPIFFE workload identity support is enabled for the domain.
	Enabled *bool `json:"enabled,omitempty"`

	// FetchTimeoutMs Timeout, in milliseconds, for fetching trust bundles.
	FetchTimeoutMs *int32 `json:"fetchTimeoutMs,omitempty"`

	// MaxJwtLifetimeSeconds Maximum accepted JWT lifetime, in seconds, computed as exp minus iat.
	MaxJwtLifetimeSeconds *int32 `json:"maxJwtLifetimeSeconds,omitempty"`

	// MaxResponseSizeKb Maximum trust bundle response size, in kilobytes.
	MaxResponseSizeKb *int32 `json:"maxResponseSizeKb,omitempty"`
}

// TokenExchangeClaimMapping Copies a claim from the validated subject or actor token onto the issued token.
type TokenExchangeClaimMapping struct {
	// Source The validated token the claim is read from.
	Source *TokenExchangeClaimMappingSource `json:"source,omitempty"`

	// SourceClaim The name of the claim on the source token.
	SourceClaim *string `json:"sourceClaim,omitempty"`

	// TokenClaim The name the claim takes on the issued token.
	TokenClaim *string `json:"tokenClaim,omitempty"`
}

// TokenExchangeClaimMappingSource The validated token the claim is read from.
type TokenExchangeClaimMappingSource string

// TokenExchangeOAuthSettings OAuth-specific token-exchange behavior, such as how scopes are handled, with optional inheritance from domain defaults.
type TokenExchangeOAuthSettings struct {
	// ClaimMappings Claims copied from the validated subject or actor token onto the issued token. A claim that is absent from its source token is skipped.
	ClaimMappings *[]TokenExchangeClaimMapping `json:"claimMappings,omitempty"`

	// Inherited Whether these settings are inherited from the domain defaults rather than defined here.
	Inherited *bool `json:"inherited,omitempty"`

	// ScopeHandling How scopes are handled when issuing the exchanged token. DOWNSCOPING restricts the issued token to a subset of the original scopes.
	ScopeHandling *TokenExchangeOAuthSettingsScopeHandling `json:"scopeHandling,omitempty"`
}

// TokenExchangeOAuthSettingsScopeHandling How scopes are handled when issuing the exchanged token. DOWNSCOPING restricts the issued token to a subset of the original scopes.
type TokenExchangeOAuthSettingsScopeHandling string

// TokenExchangeSettings OAuth 2.0 Token Exchange (RFC 8693) configuration for the domain, covering impersonation and delegation.
type TokenExchangeSettings struct {
	// AllowDelegation Whether delegation is allowed, where an actor acts on behalf of the subject and an "act" claim is added to the issued token. At least one of allowImpersonation or allowDelegation must be enabled.
	AllowDelegation *bool `json:"allowDelegation,omitempty"`

	// AllowImpersonation Whether impersonation is allowed, where the issued token represents the subject directly. At least one of allowImpersonation or allowDelegation must be enabled.
	AllowImpersonation *bool `json:"allowImpersonation,omitempty"`

	// AllowedActorTokenTypes Token types accepted as the actor token when delegating.
	//
	// Example: ["urn:ietf:params:oauth:token-type:access_token","urn:ietf:params:oauth:token-type:id_token"]
	AllowedActorTokenTypes *[]string `json:"allowedActorTokenTypes,omitempty"`

	// AllowedRequestedTokenTypes Token types that may be requested as the result of an exchange.
	//
	// Example: ["urn:ietf:params:oauth:token-type:access_token","urn:ietf:params:oauth:token-type:id_token"]
	AllowedRequestedTokenTypes *[]string `json:"allowedRequestedTokenTypes,omitempty"`

	// AllowedSubjectTokenTypes Token types accepted as the subject token in an exchange.
	//
	// Example: ["urn:ietf:params:oauth:token-type:access_token","urn:ietf:params:oauth:token-type:id_token"]
	AllowedSubjectTokenTypes *[]string `json:"allowedSubjectTokenTypes,omitempty"`

	// Enabled Whether token exchange is enabled for the domain.
	Enabled *bool `json:"enabled,omitempty"`

	// MaxDelegationDepth Maximum depth of the delegation chain (nested "act" claims). Clamped to the range 1–100.
	MaxDelegationDepth *int32 `json:"maxDelegationDepth,omitempty"`

	// TokenExchangeOAuthSettings OAuth-specific token-exchange behavior, such as how scopes are handled, with optional inheritance from domain defaults.
	TokenExchangeOAuthSettings *TokenExchangeOAuthSettings `json:"tokenExchangeOAuthSettings,omitempty"`

	// TrustedIssuers External issuers whose JWTs may be accepted as subject or actor tokens. When unset, only domain-issued tokens are accepted.
	TrustedIssuers *[]TrustedIssuer `json:"trustedIssuers,omitempty"`
}

// TrustedIssuer An external token issuer whose JWTs are accepted as subject or actor tokens during token exchange, validated with the configured key material.
type TrustedIssuer struct {
	// Certificate PEM-encoded X.509 certificate. Required when keyResolutionMethod is PEM.
	Certificate *string `json:"certificate,omitempty"`

	// Issuer Expected value of the "iss" claim in the external JWT.
	//
	// Example: https://issuer.example.com
	Issuer *string `json:"issuer,omitempty"`

	// JwksUri JWKS endpoint URL. Required when keyResolutionMethod is JWKS_URL.
	//
	// Example: https://issuer.example.com/.well-known/jwks.json
	JwksUri *string `json:"jwksUri,omitempty"`

	// KeyResolutionMethod How the issuer's signing key is resolved. JWKS_URL fetches keys from a JWKS endpoint; PEM uses an inline X.509 certificate.
	KeyResolutionMethod *TrustedIssuerKeyResolutionMethod `json:"keyResolutionMethod,omitempty"`

	// ScopeMappings One-to-one mapping from external scope to domain scope. Unmapped issuer scopes are dropped (fail-closed).
	ScopeMappings *map[string]string `json:"scopeMappings,omitempty"`

	// UserBindingCriteria Criteria used to locate a domain user when user binding is enabled. All criteria are combined with AND.
	UserBindingCriteria *[]UserBindingCriterion `json:"userBindingCriteria,omitempty"`

	// UserBindingEnabled Whether the external JWT subject is resolved to a single domain user using the user binding criteria. When false, a virtual user is built from the token claims only.
	UserBindingEnabled *bool `json:"userBindingEnabled,omitempty"`
}

// TrustedIssuerKeyResolutionMethod How the issuer's signing key is resolved. JWKS_URL fetches keys from a JWKS endpoint; PEM uses an inline X.509 certificate.
type TrustedIssuerKeyResolutionMethod string

// UMASettings Configuration of the domain's User-Managed Access (UMA 2.0) authorization features.
type UMASettings struct {
	// Enabled Whether User-Managed Access is enabled for the domain.
	Enabled *bool `json:"enabled,omitempty"`
}

// UserBindingCriterion A single rule that matches a domain user attribute against a value derived from the external token claims.
type UserBindingCriterion struct {
	// Attribute Domain user attribute used for the lookup. Must match a field supported by the user repository search.
	//
	// Example: emails.value
	Attribute *string `json:"attribute,omitempty"`

	// Expression Expression evaluated against the validated token claims (variable "token") to produce the value to match.
	//
	// Example: {#token['email']}
	Expression *string `json:"expression,omitempty"`
}

// VirtualHost A host and path the domain is exposed on. The host and path combination must be unique across all domains.
type VirtualHost struct {
	// Host Hostname the domain is served on.
	//
	// Example: auth.example.com
	Host *string `json:"host,omitempty"`

	// OverrideEntrypoint Whether this virtual host overrides the organization entry point.
	OverrideEntrypoint *bool `json:"overrideEntrypoint,omitempty"`

	// Path Context path the domain is served under on this host.
	//
	// Example: /customers
	Path *string `json:"path,omitempty"`
}

// WebAuthnSettings WebAuthn (FIDO2) relying-party configuration governing passwordless and multi-factor authentication for the domain.
type WebAuthnSettings struct {
	// AttestationConveyancePreference Relying-party preference for attestation conveyance during credential creation. NONE requests no attestation, INDIRECT allows anonymized attestation, and DIRECT requests the authenticator's attestation statement.
	AttestationConveyancePreference *WebAuthnSettingsAttestationConveyancePreference `json:"attestationConveyancePreference,omitempty"`

	// AuthenticatorAttachment Preferred authenticator attachment. PLATFORM selects authenticators bound to the device (such as a fingerprint reader); CROSS_PLATFORM selects roaming authenticators (such as a security key).
	AuthenticatorAttachment *WebAuthnSettingsAuthenticatorAttachment `json:"authenticatorAttachment,omitempty"`

	// Certificates Trusted device-attestation X.509 certificates, keyed by name.
	Certificates *map[string]string `json:"certificates,omitempty"`

	// EnforceAuthenticatorIntegrity Whether to periodically re-verify that registered authenticators remain valid against the FIDO2 Metadata Service.
	EnforceAuthenticatorIntegrity *bool `json:"enforceAuthenticatorIntegrity,omitempty"`

	// EnforceAuthenticatorIntegrityMaxAge Maximum elapsed time, in seconds, since an authenticator was last verified before it is re-checked on the next passwordless login.
	EnforceAuthenticatorIntegrityMaxAge *int32 `json:"enforceAuthenticatorIntegrityMaxAge,omitempty"`

	// ForceRegistration Whether to reject registration of a credential already registered to a different user.
	ForceRegistration *bool `json:"forceRegistration,omitempty"`

	// Origin Relying-party origin; must match the browser's window.location.origin during registration and authentication ceremonies.
	//
	// Example: https://auth.example.com
	Origin *string `json:"origin,omitempty"`

	// RelyingPartyId Relying-party identifier: a domain string that scopes credentials to this entity. A credential can only be used with the relying party it was registered against.
	//
	// Example: auth.example.com
	RelyingPartyId *string `json:"relyingPartyId,omitempty"`

	// RelyingPartyName Human-readable relying-party name shown to users during ceremonies.
	//
	// Example: Example Inc.
	RelyingPartyName *string `json:"relyingPartyName,omitempty"`

	// RequireResidentKey Whether the authenticator must create a client-side resident (discoverable) credential.
	RequireResidentKey *bool `json:"requireResidentKey,omitempty"`

	// UserVerification Relying-party requirement regarding user verification during a ceremony. REQUIRED enforces verification, PREFERRED requests it when available, and DISCOURAGED avoids it.
	UserVerification *WebAuthnSettingsUserVerification `json:"userVerification,omitempty"`
}

// WebAuthnSettingsAttestationConveyancePreference Relying-party preference for attestation conveyance during credential creation. NONE requests no attestation, INDIRECT allows anonymized attestation, and DIRECT requests the authenticator's attestation statement.
type WebAuthnSettingsAttestationConveyancePreference string

// WebAuthnSettingsAuthenticatorAttachment Preferred authenticator attachment. PLATFORM selects authenticators bound to the device (such as a fingerprint reader); CROSS_PLATFORM selects roaming authenticators (such as a security key).
type WebAuthnSettingsAuthenticatorAttachment string

// WebAuthnSettingsUserVerification Relying-party requirement regarding user verification during a ceremony. REQUIRED enforces verification, PREFERRED requests it when available, and DISCOURAGED avoids it.
type WebAuthnSettingsUserVerification string

// WebProtectionSettings HTTP security headers applied to the domain's login and consent pages.
type WebProtectionSettings struct {
	// Csp Content Security Policy configuration for the domain's login and consent pages.
	Csp *CspSettings `json:"csp,omitempty"`

	// Xframe Controls whether the domain's pages may be embedded in frames on other origins.
	Xframe *XFrameSettings `json:"xframe,omitempty"`

	// Xss Controls the legacy X-XSS-Protection response header.
	Xss *XssProtectionSettings `json:"xss,omitempty"`
}

// XFrameSettings Controls whether the domain's pages may be embedded in frames on other origins.
type XFrameSettings struct {
	// Action X-Frame-Options action. Supported values: DENY, SAMEORIGIN. Leave empty to omit the header.
	//
	// Example: DENY
	Action *string `json:"action,omitempty"`

	// Enabled Whether X-Frame-Options is enabled for the domain when not inherited.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether X-Frame-Options settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `json:"inherited,omitempty"`
}

// XssProtectionSettings Controls the legacy X-XSS-Protection response header.
type XssProtectionSettings struct {
	// Action Value of the X-XSS-Protection header.
	//
	// Example: 1; mode=block
	Action *string `json:"action,omitempty"`

	// Enabled Whether X-XSS-Protection is enabled for the domain when not inherited.
	Enabled *bool `json:"enabled,omitempty"`

	// Inherited Whether X-XSS-Protection settings are inherited from the gateway defaults (gravitee.yml). When null, legacy behaviour applies: enabled=true overrides and enabled=false inherits.
	Inherited *bool `json:"inherited,omitempty"`
}

// UpsertDomainJSONRequestBody defines body for UpsertDomain for application/json ContentType.
type UpsertDomainJSONRequestBody = AutomationDomain

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListDomains List all domains
	//
	// Returns all security domains within the specified environment.
	//
	// Corresponds with GET /domains (the `ListDomains` operationId).
	ListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertDomainWithBody Create or update a domain
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with PUT /domains (the `UpsertDomain` operationId).
	UpsertDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpsertDomain Create or update a domain
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with PUT /domains (the `UpsertDomain` operationId).
	UpsertDomain(ctx context.Context, body UpsertDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteDomain Delete a domain
	//
	// Deletes an Automation-managed domain. Deletion cascades to the domain's sub-resources (certificates, identity providers, and reporters). Deleting a domain that does not exist also returns 204.
	//
	// Corresponds with DELETE /domains/{domainKey} (the `DeleteDomain` operationId).
	DeleteDomain(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDomain Get a domain
	//
	// Retrieves a single Automation-managed security domain by its key.
	//
	// Corresponds with GET /domains/{domainKey} (the `GetDomain` operationId).
	GetDomain(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListDomains List all domains
//
// Returns all security domains within the specified environment.
//
// Corresponds with GET /domains (the `ListDomains` operationId).
func (c *Client) ListDomains(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListDomainsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertDomainWithBody Create or update a domain
//
// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
//
// Takes any type of body and a specified content type.
//
// Corresponds with PUT /domains (the `UpsertDomain` operationId).
func (c *Client) UpsertDomainWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertDomainRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// UpsertDomain Create or update a domain
//
// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with PUT /domains (the `UpsertDomain` operationId).
func (c *Client) UpsertDomain(ctx context.Context, body UpsertDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpsertDomainRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteDomain Delete a domain
//
// Deletes an Automation-managed domain. Deletion cascades to the domain's sub-resources (certificates, identity providers, and reporters). Deleting a domain that does not exist also returns 204.
//
// Corresponds with DELETE /domains/{domainKey} (the `DeleteDomain` operationId).
func (c *Client) DeleteDomain(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteDomainRequest(c.Server, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetDomain Get a domain
//
// Retrieves a single Automation-managed security domain by its key.
//
// Corresponds with GET /domains/{domainKey} (the `GetDomain` operationId).
func (c *Client) GetDomain(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDomainRequest(c.Server, domainKey)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListDomainsRequest constructs an http.Request for the ListDomains method
func NewListDomainsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpsertDomainRequest calls the generic UpsertDomain builder with application/json body
func NewUpsertDomainRequest(server string, body UpsertDomainJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpsertDomainRequestWithBody(server, "application/json", bodyReader)
}

// NewUpsertDomainRequestWithBody constructs an http.Request for the UpsertDomain method, with any body, and a specified content type
func NewUpsertDomainRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPut, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteDomainRequest constructs an http.Request for the DeleteDomain method
func NewDeleteDomainRequest(server string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDomainRequest constructs an http.Request for the GetDomain method
func NewGetDomainRequest(server string, domainKey string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "domainKey", domainKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/domains/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListDomainsWithResponse List all domains
	//
	// Returns all security domains within the specified environment.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains (the `ListDomains` operationId).
	ListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDomainsResponse, error)

	// UpsertDomainWithBodyWithResponse Create or update a domain
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains (the `UpsertDomain` operationId).
	UpsertDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertDomainResponse, error)

	// UpsertDomainWithResponse Create or update a domain
	//
	// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with PUT /domains (the `UpsertDomain` operationId).
	UpsertDomainWithResponse(ctx context.Context, body UpsertDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertDomainResponse, error)

	// DeleteDomainWithResponse Delete a domain
	//
	// Deletes an Automation-managed domain. Deletion cascades to the domain's sub-resources (certificates, identity providers, and reporters). Deleting a domain that does not exist also returns 204.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with DELETE /domains/{domainKey} (the `DeleteDomain` operationId).
	DeleteDomainWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*DeleteDomainResponse, error)

	// GetDomainWithResponse Get a domain
	//
	// Retrieves a single Automation-managed security domain by its key.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /domains/{domainKey} (the `GetDomain` operationId).
	GetDomainWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*GetDomainResponse, error)
}

type ListDomainsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]AutomationDomain
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListDomainsResponse) GetJSON200() *[]AutomationDomain {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r ListDomainsResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r ListDomainsResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r ListDomainsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListDomainsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListDomainsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListDomainsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type UpsertDomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationDomain
	// JSON400 the response for an HTTP 400 `application/json` response
	JSON400 *Error
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r UpsertDomainResponse) GetJSON200() *AutomationDomain {
	return r.JSON200
}

// GetJSON400 returns the response for an HTTP 400 `application/json` response
func (r UpsertDomainResponse) GetJSON400() *Error {
	return r.JSON400
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r UpsertDomainResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetBody returns the raw response body bytes
func (r UpsertDomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r UpsertDomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpsertDomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r UpsertDomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DeleteDomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *Error
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r DeleteDomainResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r DeleteDomainResponse) GetJSONDefault() *Error {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r DeleteDomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r DeleteDomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteDomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DeleteDomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetDomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *AutomationDomain
	// JSON403 the response for an HTTP 403 `application/json` response
	JSON403 *Error
	// JSON404 the response for an HTTP 404 `application/json` response
	JSON404 *Error
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetDomainResponse) GetJSON200() *AutomationDomain {
	return r.JSON200
}

// GetJSON403 returns the response for an HTTP 403 `application/json` response
func (r GetDomainResponse) GetJSON403() *Error {
	return r.JSON403
}

// GetJSON404 returns the response for an HTTP 404 `application/json` response
func (r GetDomainResponse) GetJSON404() *Error {
	return r.JSON404
}

// GetBody returns the raw response body bytes
func (r GetDomainResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetDomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetDomainResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListDomainsWithResponse List all domains
//
// Returns all security domains within the specified environment.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains (the `ListDomains` operationId).
func (c *ClientWithResponses) ListDomainsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListDomainsResponse, error) {
	rsp, err := c.ListDomains(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListDomainsResponse(rsp)
}

// UpsertDomainWithBodyWithResponse Create or update a domain
//
// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains (the `UpsertDomain` operationId).
func (c *ClientWithResponses) UpsertDomainWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpsertDomainResponse, error) {
	rsp, err := c.UpsertDomainWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertDomainResponse(rsp)
}

// UpsertDomainWithResponse Create or update a domain
//
// Idempotent create-or-update. Uses the key field in the body to identify the domain. On first apply the domain is created; subsequent applies update it. dataPlaneId is optional at creation, resolved from the environment's data planes when omitted, and immutable afterwards.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with PUT /domains (the `UpsertDomain` operationId).
func (c *ClientWithResponses) UpsertDomainWithResponse(ctx context.Context, body UpsertDomainJSONRequestBody, reqEditors ...RequestEditorFn) (*UpsertDomainResponse, error) {
	rsp, err := c.UpsertDomain(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpsertDomainResponse(rsp)
}

// DeleteDomainWithResponse Delete a domain
//
// Deletes an Automation-managed domain. Deletion cascades to the domain's sub-resources (certificates, identity providers, and reporters). Deleting a domain that does not exist also returns 204.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with DELETE /domains/{domainKey} (the `DeleteDomain` operationId).
func (c *ClientWithResponses) DeleteDomainWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*DeleteDomainResponse, error) {
	rsp, err := c.DeleteDomain(ctx, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteDomainResponse(rsp)
}

// GetDomainWithResponse Get a domain
//
// Retrieves a single Automation-managed security domain by its key.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /domains/{domainKey} (the `GetDomain` operationId).
func (c *ClientWithResponses) GetDomainWithResponse(ctx context.Context, domainKey string, reqEditors ...RequestEditorFn) (*GetDomainResponse, error) {
	rsp, err := c.GetDomain(ctx, domainKey, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDomainResponse(rsp)
}

// ParseListDomainsResponse parses an HTTP response from a ListDomainsWithResponse call
func ParseListDomainsResponse(rsp *http.Response) (*ListDomainsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListDomainsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []AutomationDomain
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseUpsertDomainResponse parses an HTTP response from a UpsertDomainWithResponse call
func ParseUpsertDomainResponse(rsp *http.Response) (*UpsertDomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpsertDomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationDomain
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ParseDeleteDomainResponse parses an HTTP response from a DeleteDomainWithResponse call
func ParseDeleteDomainResponse(rsp *http.Response) (*DeleteDomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteDomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.StatusCode == 204:
		break // No content-type

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetDomainResponse parses an HTTP response from a GetDomainWithResponse call
func ParseGetDomainResponse(rsp *http.Response) (*GetDomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest AutomationDomain
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
